packages/builder/package.json
upgrade webpack-dev-server version to avoid dangerous
=> chore: upgrade webpack-dev-server

package.json, packages/antd/index.d.ts, packages/antd/package.json, packages/react/index.d.ts, packages/react/package.json
Currently I have defined some types, the scope is: antd, part of react
=> feat(packages): some the antd component and the react component

packages/antd/src/components/button.js, packages/next/src/components/button.js
其实 antd 那边也加上了。
主要的功能就是 submit 的时候, showLoading 时候点击会加上 disabled 效果, 防止二次点击。
在 yuque 编辑的时候已经有这样子的功能了, 所以这个交互应该是合理通用的。
第一次搞, 不太了解整个流程哈, 大佬看下还需要加啥。
=> feat(@uform/next): add disabled when loading

scripts/validate-commit-msg.js
很明显 https://github.com/alibaba/uform/.github/GIT_COMMIT_SPECIFIC.md 这个是 404
=> chore(scripts): correct git commit specific url

packages/core/src/form.js, packages/react/src/__tests__/actions.spec.js
call setFieldState function more than once at the same time can not resolve all returned promise
fix #23
=> fix(core/form): setFieldState bug

docs/Examples/antd/Detail.md, docs/Examples/antd/International.md, docs/Examples/antd/Relations.md, docs/Examples/antd/Sample.md, packages/antd/src/utils.js
https://github.com/alibaba/uform/issues/107
=> fix: antd select should not have max-width by default

packages/antd/src/form.js
因为uform对antd form的支持遗漏了默认form layout，所以在窄屏下效果较差
=> feat(@uform/antd): support form layout properties

docs/API/SchemaForm.md, docs/API/connect.md, packages/antd/src/form.js, packages/next/src/form.js
考虑有些时候业务上的要求，针对description==>popTips展示效果的限制会有特殊要求，所以提供单独配置口子做配置
=> feat(@uform/core): support maxTipsNum

docs/API/Field_React.md, docs/API/SchemaForm_React.md, docs/SUMMARY.md, docs/Tutorials/Questions.md, packages/antd/src/fields/array.js, packages/antd/src/fields/cards.js, packages/antd/src/fields/table.js, packages/antd/src/form.js, packages/core/src/form.js, packages/next/src/fields/array.js, packages/next/src/fields/cards.js, packages/next/src/fields/table.js, packages/next/src/form.js, packages/react/src/__tests__/effects.spec.js, packages/utils/src/accessor.js
1. 修复antd/next array list classname传递问题
2. 修复utils中setIn的值更新异常问题
3. 修复setFieldState推入缓冲区，路径匹配问题
4. 完善文档，增加了 常见问题
=> bugfix and update docs

packages/core/package.json, packages/core/src/utils.js
to solve https://github.com/alibaba/uform/issues/140
=> feat: make scheduler optional

docs/API/Field_React.md, docs/API/FormButtonGroup.md, docs/API/FormConsumer.md, docs/API/FormItemGrid.md, docs/API/FormLayout.md, docs/API/FormPath.md, docs/API/FormTextBox.md, docs/API/SchemaForm.md, docs/API/SchemaForm_React.md, docs/API/Submit.md, docs/API/connect.md, docs/API/createAsyncFormActions.md, docs/API/createForm.md, docs/API/createFormActions.md, docs/API/createVirtualBox.md, docs/API/registerFieldMiddleware.md, docs/API/registerFormField.md, docs/API/registerFormFields.md, docs/API/registerFormWrapper.md, docs/API/setValidationLanguage.md, docs/API/setValidationLocale.md
使用ts来标注api
refer: https://github.com/alibaba/uform/issues/103
=> feat: update the api docs using typescript 

docs/API/createForm.md
=> docs: add detail of createForm

docs/API/createAsyncFormActions.md, docs/API/createForm.md, docs/API/createFormActions.md, docs/Examples/next/Detail.md, packages/core/src/form.ts, packages/react/src/state/form.tsx
=> feat(@uform/core): support reset noValidate

docs/API/createForm.md, packages/core/src/field.ts, packages/core/src/form.ts, packages/core/src/index.ts, packages/react/src/__tests__/context.spec.js, packages/react/src/shared/broadcast.tsx, packages/react/src/shared/context.tsx, packages/react/src/shared/mutators.ts, packages/react/src/state/field.tsx, packages/react/src/state/form.tsx, packages/react/src/type.ts, packages/types/src/form.ts, packages/utils/src/clone.ts
优化状态广播系统，同时对FormConsumer支持selector的能力
=> feat(@uform/react): Feat improve broadcast

docs/Examples/antd/Deconstruction.md, docs/Examples/next/Deconstruction.md, docs/Examples/next/Relations.md, docs/SUMMARY.md, packages/printer/src/index.js, packages/react/src/__tests__/context.spec.js, packages/utils/src/__tests__/index.spec.js, packages/utils/src/accessor.ts, packages/validator/src/validators/required.ts
=> feat(docs): support deconstruction

packages/core/src/form.ts, packages/core/src/index.ts, packages/react/src/__tests__/traverse.spec.js, packages/react/src/state/field.tsx, packages/react/src/state/form.tsx, packages/types/src/form.ts
=> fix(@uform/core): fix field props transformer is not work

package.json, packages/builder/src/__tests__/actions/index.spec.js, packages/builder/src/__tests__/comp.spec.js, packages/builder/src/components/fields/field.js, packages/builder/src/components/globalBtnList/index.js, packages/builder/src/components/index.js, packages/builder/src/components/props/editors/fieldAttrEditors/defaultValueEditor/monthDefaultEditor.js, packages/builder/src/constants/context.js, packages/builder/src/reducers/componentProps.js, packages/builder/src/reducers/initSchemaData.js, packages/builder/src/style.js, packages/builder/src/utils/util.js, packages/core/src/form.ts, packages/next/src/fields/table.js, packages/next/src/utils.js, packages/printer/src/index.js, packages/react/src/__tests__/actions.spec.js, packages/react/src/__tests__/context.spec.js, packages/react/src/__tests__/traverse.spec.js, packages/react/src/__tests__/value.spec.js, packages/react/src/__tests__/visible.spec.js, packages/utils/src/__tests__/index.spec.js, packages/utils/src/accessor.ts
=> Fix number key will create array

docs/API/Submit.md
=> docs(Submit): fix table style

packages/antd/src/utils.tsx
=> fix(@uform/antd): Fix Antd Input loading state automatically loses focus

README.md
=> chore(docs): UForm name typo

docs/Examples/antd/Sample.md, packages/antd/src/fields/upload.tsx
=> fix(@uform/antd): fix antd upload

docs/Examples/antd/Detail.md, docs/Examples/antd/International.md, docs/Examples/antd/Sample.md, docs/Tutorials/快速入门.md, packages/antd/src/fields/date.tsx
=> Feat:  add week component type

docs/Examples/antd/Layout.md, docs/Examples/next/Layout.md, packages/antd/src/components/layout.tsx, packages/next/src/components/layout.tsx
Fix #231 
因为createVirtualBox无法获取全部的props，所以拿不到表单的editable属性，就无法根据editable属性设置margin值，所以改用createControllerBox来实现该功能
=> fix FormTextBox margin value

packages/antd/src/fields/upload.tsx
Reverts alibaba/uform#252 是antd的bug
=> Revert "fix(@uform/antd): fix antd upload types"

docs/Examples/next/Detail.md
=> fix(examples): remove the onChange of next/Detail

packages/core/src/utils.ts, packages/types/package.json, scripts/docs.js
=> fix docs build errors

.travis.yml
确保 根目录 的依赖跟 packages 下各个包的依赖都是最新的
=> chore(travis): Guaranteed dependency peering

packages/core/src/form.ts, packages/react/src/__tests__/validate.spec.js
fix #265
最简单的处理方案，只需要在submit的时候阻塞调用即可
=> fix(@uform/core): fix async validate prevent submit

packages/core/src/form.ts, packages/react/src/__tests__/validate.spec.js, packages/validator/src/index.ts
=> Fix validate side effect

packages/utils/src/globalThis.ts
=> fix(globalThis): fix ReferenceError

packages/core/src/__tests__/lifecycle.spec.ts
=> [WIP]feat(core): add lifecycles unit test

packages/core/src/__tests__/graph.spec.ts, packages/core/src/__tests__/lifecycle.spec.ts, packages/core/src/shared/graph.ts
=> feat(core): add graph unit test 

package.json, packages/react-schema-renderer/src/__tests__/actions.spec.tsx, packages/react-schema-renderer/src/__tests__/context.spec.tsx, packages/react-schema-renderer/src/__tests__/destruct.spec.tsx, packages/react-schema-renderer/src/__tests__/display.spec.tsx, packages/react-schema-renderer/src/__tests__/dynamic.spec.tsx, packages/react-schema-renderer/src/__tests__/editable.spec.tsx, scripts/global.js, scripts/global.ts, scripts/jest.base.js
=> test(@uform/react-schema-renderer): add old test case

package.json, packages/core/src/__tests__/field.state.spec.ts, packages/core/src/__tests__/form.state.spec.ts, packages/core/src/__tests__/model.spec.ts, packages/core/src/__tests__/vfield.state.spec.ts, packages/core/src/index.ts, packages/core/src/shared/model.ts, packages/core/src/types.ts, packages/react-schema-renderer/src/__old_tests__/dynamic.spec.js, packages/react-schema-renderer/src/__tests__/actions.spec.tsx, packages/react-schema-renderer/src/__tests__/context.spec.tsx, packages/react-schema-renderer/src/__tests__/destruct.spec.tsx, packages/react-schema-renderer/src/__tests__/display.spec.tsx, packages/react-schema-renderer/src/__tests__/dynamic.spec.tsx, packages/react-schema-renderer/src/__tests__/editable.spec.tsx, packages/react-schema-renderer/src/components/SchemaField.tsx, packages/react-schema-renderer/src/components/SchemaForm.tsx, packages/react-schema-renderer/src/shared/registry.ts, packages/react-schema-renderer/src/shared/schema.ts, packages/react/src/components/FormConsumer.tsx, packages/react/src/components/FormSpy.tsx, packages/react/src/hooks/useField.ts, packages/react/src/hooks/useForm.ts, packages/react/src/shared.ts, packages/shared/src/deprecate.ts
=> test(@uform/react-schema-renderer): fix test case uncompat bugs

packages/antd/src/fields/date.tsx
=> fix(antd): return null while date field value are empty string or other falsy value (fix #367)

packages/antd/src/fields/time.tsx
=> fix(antd): return null while time field get falsy value (fix #371)

packages/core/src/__tests__/index.spec.ts, packages/core/src/index.ts, packages/core/src/types.ts
1. setFormState第二个参数应该是silent，透传到form.setState，之前遗漏了
2. setFieldState第二个参数应该是silent，透传到field.setState，之前遗漏了
3. setFieldValue, setFieldInitialValue 同理
4. 相关单测
=> feat: add silent option

packages/core/README.md, packages/core/README.zh-cn.md
=> docs: fix typo and improve docs

packages/react/README.md, packages/react/README.zh-cn.md, packages/react/src/hooks/useFormSpy.ts, packages/react/src/types.ts
1.  增加显示/隐藏文档
2. 增加异步联动文档
3. 增加联动校验文档
4. 增加复杂联动(ArrayField)
5. 增加visible/display例子文档
=> 增加react联动文档

packages/shared/src/__tests__/index.spec.ts, packages/shared/src/types.ts
Fix this problem https://github.com/alibaba/uform/issues/409
=> Fix isFn can't test async function

packages/react-shared-components/src/PreviewText.tsx
=> fix(@uform/react-shared-components): fix preview

packages/react/src/__tests__/vfield.spec.tsx, packages/react/src/types.ts
add field and virtualField test case
=> test(@uform/react): improve field and virtualField test cases

package.json, packages/react-schema-editor/src/__tests__/index.spec.ts, packages/react-schema-editor/src/utils/json2schema.ts
=> feat: json to basic schema

packages/react-schema-renderer/src/shared/schema.ts, packages/react-schema-renderer/src/types.ts
=> fix(@uform/react-schema-renderer): fix typings

packages/core/README.md, packages/core/README.zh-cn.md, packages/core/src/__tests__/field.state.spec.ts, packages/core/src/__tests__/form.state.spec.ts, packages/core/src/__tests__/graph.spec.ts, packages/core/src/__tests__/model.spec.ts, packages/core/src/__tests__/vfield.state.spec.ts, packages/core/src/index.ts, packages/core/src/shared/model.ts, packages/core/src/types.ts, packages/react/src/hooks/useFieldState.ts
=> fix(@uform/core): fix sync value

docs/Examples/antd/Actions.md, docs/Examples/antd/Deconstruction.md, docs/Examples/antd/Detail.md, docs/Examples/antd/International.md, docs/Examples/antd/Layout.md, docs/Examples/antd/List.md, docs/Examples/antd/Relations.md, docs/Examples/antd/Sample.md, docs/Examples/antd/Validation.md, docs/Examples/next/Actions.md, docs/Examples/next/Deconstruction.md, docs/Examples/next/Detail.md, docs/Examples/next/International.md, docs/Examples/next/Layout.md, docs/Examples/next/List.md, docs/Examples/next/Relations.md, docs/Examples/next/Sample.md, docs/Examples/next/Validation.md, packages/antd/README.md, packages/antd/README.zh-cn.md, packages/next/README.md, packages/next/README.zh-cn.md
1. add antd/react hook document
2. enhanced V0 example
=> fix(@uform/antd/next/react): doc

packages/antd/README.md, packages/antd/README.zh-cn.md, packages/next/README.md, packages/next/README.zh-cn.md, packages/react/README.md, packages/react/README.zh-cn.md, packages/react/src/__tests__/useFieldState.spec.tsx, packages/react/src/__tests__/useFormEffects.spec.tsx, packages/react/src/__tests__/useFormState.spec.tsx, packages/react/src/hooks/useFormEffects.ts
1. specific useFormEffects start from `ON_FORM_MOUNT` lifecylce
2. add useFormEffects unit-test
3. add useFormState unit-test
4. add useFieldState unit-test
=> feat: update unitest and document

packages/next/README.zh-cn.md, packages/shared/src/deprecate.ts
=> fix(@uform/shared/react): fix depreated and get schema

package.json, packages/core/package.json, packages/react/package.json
=> fix: build on windows

packages/core/src/__tests__/index.spec.ts, packages/core/src/index.ts, packages/react/src/__tests__/actions.spec.tsx, packages/react/src/__tests__/form.spec.tsx
=> fix: (issue#543)

package.json, packages/react-shared-components/src/ArrayList.tsx, packages/react-shared-components/src/PreviewText.tsx, packages/react-shared-components/src/__tests__/index.spec.tsx, packages/react-shared-components/src/__tests__/useArrayList.spec.tsx, packages/react-shared-components/src/context.ts, packages/react-shared-components/src/hooks/useArrayList.tsx, packages/react-shared-components/src/hooks/useComponent.tsx, packages/react-shared-components/src/types.ts
Fixes #540 
add unit test for `useArrayList`
=> fix: issue#540

packages/antd/README.md, packages/antd/README.zh-cn.md, packages/antd/src/types.ts, packages/core/src/index.ts, packages/next/README.md, packages/next/README.zh-cn.md, packages/next/src/types.ts, packages/react-schema-renderer/src/shared/schema.ts
1. add validateRules in document of antd/next
2. deprecated x-render
=> featfix(@uform/react-schema-renderer/antd/next) doc and depreacate x-render

packages/antd/src/fields/date.tsx, packages/core/src/index.ts
=> Fix: date picker warning

docs/Examples/next/Layout.md
=> docs: update readme

packages/react-schema-renderer/src/__tests__/schema.spec.tsx, packages/react-schema-renderer/src/shared/schema.ts, packages/react-schema-renderer/src/types.ts
=> Chore: depreate getExtendItemProps

packages/antd/src/fields/date.tsx, packages/antd/src/fields/table.tsx, packages/next/src/fields/table.tsx
=> fix: 620/617

packages/antd/src/fields/table.tsx, packages/next/src/fields/table.tsx
复现地址 https://codesandbox.io/s/wizardly-haibt-vgm3z
=> fix(antd): table内无法解构arr[0]这样的类型

packages/.eslintrc, packages/next/src/fields/table.tsx, packages/next/src/types.ts, packages/react-schema-editor/src/index.tsx, packages/shared/src/deprecate.ts
=> fix: fix type lint

packages/next/src/fields/upload.tsx
=> fix( upload ): miss children propertity of fusion

packages/react-schema-editor/README.md, packages/react-schema-editor/src/__tests__/index.spec.ts, packages/react-schema-editor/src/components/JsonDialog.tsx, packages/react-schema-editor/src/index.tsx, packages/react-schema-editor/src/utils/json2schema.ts
=> feat: schema editor support json to schema

packages/antd/src/index.tsx, packages/next/src/index.tsx, packages/react-schema-renderer/src/shared/expression.ts
1. 默认导出SchemaForm组件
2. 修复递归编译表达式过程中遇到循环引用对象报错的问题
=> fix(project): compat uform

packages/antd/src/components/FormItem.tsx, packages/next/src/components/FormItem.tsx, packages/react-schema-renderer/src/components/SchemaField.tsx
remove empty field component rendering
=> Feat no component tips

docs/zh-cn/schema-develop/faq.md, packages/core/src/__tests__/index.spec.ts, packages/core/src/index.ts, packages/react-schema-renderer/src/__tests__/dynamic.spec.tsx
=> fix(@formily/core): fix onChange trigger times issue#644

packages/antd/README.zh-cn.md, packages/next/README.zh-cn.md
feat: add components and hooks
=> feat: add components and hooks

packages/antd-components/README.zh-cn.md, packages/antd-components/src/date-picker/index.tsx
1. 修复了 YearPicker 选择无效的问题（修复后仅支持 antd V4）
2. 修复了 Transfer Item 的 title 属性不渲染的问题
3. 文档中补充了缺失的内置组件类型
=> Fix antd-components package

packages/antd/README.zh-cn.md, packages/next/README.zh-cn.md
=> doc: update doc of component

packages/antd-components/README.zh-cn.md, packages/next-components/README.zh-cn.md
=> fix: doc typo of antd

packages/antd-components/README.zh-cn.md, packages/antd/README.zh-cn.md, packages/core/src/types.ts, packages/next/README.zh-cn.md
=> doc: add form and formitem

packages/antd/src/adaptor/FormItem.tsx, packages/next/src/adaptor/FormItem.tsx
=> fix(antd/next): fix layout can not pass FormItem attributes

docs/zh-cn/jsx-develop/lifecycle.md, docs/zh-cn/schema-develop/lifecycle.md, package.json, packages/antd/README.zh-cn.md, packages/core/README.md, packages/core/README.zh-cn.md, packages/core/src/index.ts, packages/core/src/types.ts, packages/meet/README.zh-cn.md, packages/next/README.zh-cn.md, packages/react/README.md, packages/react/README.zh-cn.md, packages/react/src/shared.ts
1. add onSubmit success/failed hook
2. add IFormProps interface doc
=> feat(hooks): add onSubmit hook and docs

docs/zh-cn/schema-develop/manage-business.md, packages/antd-components/package.json, packages/core/src/index.ts
=> docs(practice): add manage-business.md

docs/zh-cn/SUMMARY.md, docs/zh-cn/jsx-develop/self-inc-component.md, docs/zh-cn/schema-develop/complext-self-inc-component.md, docs/zh-cn/schema-develop/self-inc-component.md, packages/antd-components/src/array-table/index.tsx, packages/antd/README.zh-cn.md, packages/next/README.zh-cn.md
=> doc(next/antd): add document of array items

docs/zh-cn/jsx-develop/faq.md, packages/core/src/index.ts, packages/react-schema-renderer/src/linkages/schema.ts, packages/react-schema-renderer/src/linkages/state.ts
=> fix(core): fix unmount onChange trigger and x-linkages array merge

packages/antd-components/src/array-table/index.tsx, packages/next-components/src/array-table/index.tsx
=> Array table: Do not render the operation area when editable is false or operations is false

packages/react-schema-renderer/src/shared/connect.ts
=> fix(schema-renderer): fix onBlur/onFocus

packages/antd/src/shared.ts, packages/react-schema-renderer/src/shared/connect.ts
=> fix(antd): fix error auto scroll is not work for antd4

packages/shared/src/array.ts
toArr 方法入参为 Proxy 时在 iOS10 下的兼容性：https://github.com/alibaba/formily/issues/759
=> fix(share): fix toArr if param is a proxy

packages/core/src/index.ts, packages/core/src/shared/lifecycle.ts
=> fix(core): Fix the wrong publishing sequence of initialization events

packages/antd-components/src/form-step/index.tsx, packages/next-components/src/form-step/index.tsx
=> fix(antd/next-components): formStep support current attribute

packages/core/src/index.ts, packages/react-schema-renderer/src/__tests__/validate.spec.tsx, packages/react/src/hooks/useField.ts, packages/shared/src/array.ts
=> fix(core): fix initialValues validate

packages/antd-components/src/array-cards/index.tsx, packages/antd-components/src/array-table/index.tsx, packages/next-components/src/array-cards/index.tsx, packages/next-components/src/array-table/index.tsx
=> fix(antd/next-components): fix array items

docs/zh-cn/schema-develop/complex-linkage.md, docs/zh-cn/schema-develop/form-schema.md, packages/react-schema-renderer/src/shared/linkage.ts
=> feat(schema-renderer): support relative target path

README.md
=> fix: README 单词拼写

packages/next/README.zh-cn.md
=> fix: 修复文档描述错误

packages/antd/README.zh-cn.md
=> fix: 修复文档中描述错误

package.json, packages/.eslintrc, packages/core/src/index.ts, packages/react-schema-renderer/src/types.ts
=> fix(core): fix destruction default value is not work and fix typings

packages/antd-components/src/registry.ts, packages/antd-components/src/time-picker/index.tsx
类似 daterange，为 TimePicker 增加 TimePicker.RangePicker 支持。
并且在 registry 增加 `timerange: TimePicker.RangePicker`
=> feat(antd-components): add TimePicker.RangePicker

docs/zh-cn/jsx-develop/quick-start.md, docs/zh-cn/schema-develop/quick-start.md
=> feat(docs): add antd TimePicker.RangePicker demo.

packages/core/src/__tests__/index.spec.ts, packages/core/src/index.ts, packages/core/src/shared/model.ts, packages/core/src/types.ts
=> fix(core): fix immer autoFreeze and reset Native Object

docs/zh-cn/SUMMARY.md, docs/zh-cn/schema-develop/form-query.md, docs/zh-cn/schema-develop/form-schema.md, docs/zh-cn/schema-develop/quick-start.md, packages/antd/src/hooks/useFormTableQuery.tsx, packages/core/src/index.ts, packages/next/src/hooks/useFormTableQuery.ts, packages/react/src/hooks/useFormQuery.ts, packages/react/src/shared.ts, packages/react/src/types.ts
=> feat(antd/next): improve useFormTableQuery

packages/next/src/adaptor/Form.tsx
=> fix(next): fix throw error when use previewPlaceholder

packages/react-schema-renderer/src/shared/connect.ts
=> fix(schema-renderer): fix onBlur throw errors #839

packages/antd-components/src/form-tab/index.tsx, packages/next-components/src/form-tab/index.tsx
=> fix(antd/next): fix form-tab typings

packages/core/src/index.ts
=> fix(core): fix unmounteRemoveValue property is not work #827

packages/antd/src/adaptor/FormItem.tsx, packages/react-schema-renderer/src/shared/connect.ts
=> fix(antd): fix labelCol/wrapperCol can not be overwriten

packages/antd-components/src/form-text-box/index.tsx, packages/next-components/src/form-text-box/index.tsx
=> fix(antd/next): fix FormTextBox doesnot support className

packages/react-schema-renderer/src/components/SchemaField.tsx
=> fix(schema-renderer): fix x-component case sensitivity

packages/antd/src/components/FormButtonGroup.tsx, packages/next/src/components/FormButtonGroup.tsx
=> fix(antd/next): fix button-group typings

packages/react-schema-editor/package.json
=> fix(schema-editor): fix dependencies

docs/zh-cn/SUMMARY.md, docs/zh-cn/jsx-develop/mega-layout-antd.md, docs/zh-cn/jsx-develop/mega-layout.md, docs/zh-cn/schema-develop/mega-layout-antd.md, docs/zh-cn/schema-develop/mega-layout.md, packages/antd/src/__tests__/__snapshots__/layout.spec.tsx.snap, packages/antd/src/__tests__/layout.spec.tsx, packages/antd/src/components/FormMegaLayout/index.tsx, packages/antd/src/components/FormMegaLayout/style.tsx, packages/next/src/__tests__/__snapshots__/layout.spec.tsx.snap, packages/next/src/__tests__/layout.spec.tsx, packages/next/src/components/FormMegaLayout/index.tsx, packages/next/src/components/FormMegaLayout/style.tsx, packages/react/src/hooks/useLayout.tsx, packages/react/src/types.ts
1. fix nested columns and responsive
2. fix performance problem by nested grid
=> fix: megalayout columns

packages/react-schema-renderer/src/shared/connect.ts
=> fix(schema-renderer): fixed connect onBlur/onFocus throw errors

packages/core/src/index.ts
=> fix(core): fix intialValues sync

packages/antd/README.zh-cn.md
docs(antd): markdown special symbol escape
=> docs(antd): markdown special symbol escape

docs/zh-cn/schema-develop/form-layout.md, packages/antd/src/__tests__/__snapshots__/layout.spec.tsx.snap, packages/antd/src/__tests__/layout.spec.tsx, packages/antd/src/components/FormMegaLayout/style.tsx, packages/next/src/__tests__/__snapshots__/layout.spec.tsx.snap, packages/next/src/__tests__/layout.spec.tsx, packages/next/src/components/FormMegaLayout/style.tsx
fix nested Megalyout span(css-grid span) and responsive problem
=> fix(layout): nested layout span and responsive

docs/zh-cn/jsx-develop/form-state.md, docs/zh-cn/schema-develop/form-state.md, packages/core/src/types.ts
=> fix(core): fix types of errors/warnings in IFormState

packages/antd-components/src/array-table/index.tsx, packages/core/src/__tests__/index.spec.ts, packages/core/src/externals.ts, packages/react/src/hooks/useFormSpy.ts
=> fix(react): fix ArrayTable index and FormSpy

docs/zh-cn/schema-develop/complext-self-inc-component.md, packages/antd/src/components/FormMegaLayout/index.tsx, packages/next/src/components/FormMegaLayout/index.tsx
add ts type desc of MegaLayout  and fix array-inc doc
=> feat(layout): add ts type desc of MegaLayout  and fix array-inc doc

packages/core/src/internals.ts, packages/core/src/shared/model.ts
=> fix(core): sync form state

docs/zh-cn/schema-develop/form-query.md, packages/antd/src/components/Button.tsx, packages/antd/src/hooks/useFormTableQuery.tsx, packages/core/src/internals.ts, packages/core/src/shared/model.ts, packages/next/src/components/Button.tsx, packages/next/src/hooks/useFormTableQuery.ts, packages/react-schema-renderer/src/__tests__/effects.spec.tsx, packages/react/src/hooks/useFormQuery.ts, packages/react/src/shared.ts
=> Fix use form table query

packages/core/src/externals.ts
=> fix(core): fix event trigger order

packages/antd/src/__tests__/__snapshots__/layout.spec.tsx.snap, packages/antd/src/components/FormMegaLayout/ie.tsx, packages/antd/src/components/FormMegaLayout/index.tsx, packages/antd/src/components/FormMegaLayout/style.tsx, packages/next/src/__tests__/__snapshots__/layout.spec.tsx.snap, packages/next/src/components/FormMegaLayout/ie.tsx, packages/next/src/components/FormMegaLayout/index.tsx, packages/next/src/components/FormMegaLayout/style.tsx
增加ie8-11的css-grid兼容，使用flex去兼容，在低版本ie下，部分css-grid功能在-ms-grid并不能实现，例如自动行列间距 gap 及自动宽度
=> feat(layout): add ie compat mode of grid(ie)

packages/antd/src/__tests__/__snapshots__/layout.spec.tsx.snap, packages/antd/src/__tests__/layout.spec.tsx, packages/antd/src/components/FormMegaLayout/ie.tsx, packages/antd/src/components/FormMegaLayout/inset.tsx, packages/antd/src/components/FormMegaLayout/style.tsx
=> feat(layout): support antd v3

packages/antd/src/components/FormMegaLayout/ie.tsx, packages/next/src/components/FormMegaLayout/ie.tsx, scripts/global.ts
=> feat(layout): support old browser grid layout

docs/zh-cn/SUMMARY.md, packages/antd/src/components/FormMegaLayout/ie.tsx, packages/antd/src/components/FormMegaLayout/index.tsx, packages/antd/src/components/FormMegaLayout/style.tsx, packages/next/src/components/FormMegaLayout/ie.tsx, packages/next/src/components/FormMegaLayout/index.tsx, packages/next/src/components/FormMegaLayout/style.tsx
=> feat(layout): support responsive gri layout for older browsers

packages/antd-components/src/array-cards/index.tsx, packages/next-components/src/array-cards/index.tsx
=> feat: add span to dot of array-cards for custom style

packages/react-schema-renderer/src/__tests__/schema.spec.tsx, packages/react-schema-renderer/src/__tests__/validate.spec.tsx, packages/react-schema-renderer/src/shared/schema.ts
=> fix(schema): issue 853 and 860

packages/core/src/internals.ts, packages/core/src/models/field.ts
=> fix(core): fix form change trigger

packages/antd/src/components/FormMegaLayout/index.tsx, packages/next/src/components/FormMegaLayout/index.tsx
=> FormMegaLayout 增加className

packages/core/src/internals.ts
=> fix(@formily/core): 修复启用/禁用unmountClearStates时的标识赋值错误问题

packages/core/src/externals.ts, packages/core/src/models/field.ts
=> fix(core): fix array move

packages/core/src/externals.ts, packages/core/src/internals.ts, packages/core/src/types.ts
=> fix(core): fix array list move algorithm

docs/zh-cn/schema-develop/mega-layout-antd.md, docs/zh-cn/schema-develop/mega-layout.md, packages/antd-components/src/password/index.tsx, packages/antd/src/__tests__/__snapshots__/layout.spec.tsx.snap, packages/antd/src/__tests__/layout.spec.tsx, packages/antd/src/components/FormMegaLayout/ie.tsx, packages/antd/src/components/FormMegaLayout/index.tsx, packages/antd/src/components/FormMegaLayout/style.tsx, packages/next/src/__tests__/__snapshots__/layout.spec.tsx.snap, packages/next/src/__tests__/layout.spec.tsx, packages/next/src/components/FormMegaLayout/ie.tsx, packages/next/src/components/FormMegaLayout/index.tsx, packages/next/src/components/FormMegaLayout/style.tsx, packages/react/src/hooks/useLayout.tsx, packages/react/src/types.ts
compat antv3 and fix layout related issue
Fixes #942 
Fixes #937 
Fixes #923
=> feat(layout): compat antv3 and fix layout related issue

packages/validator/src/validator.ts
=> perf(validator): improve validate perf

packages/react-schema-renderer/src/__tests__/actions.spec.tsx, packages/react-schema-renderer/src/shared/expression.ts
=> fix(schema): compat eva expression actions

packages/core/src/internals.ts
=> fix(core): fix form ref values

packages/core/src/externals.ts, packages/shared/src/merge.ts
=> fix(core): fix move down throw errors and fix null assign merge throw errors

packages/antd/src/components/FormMegaLayout/index.tsx, packages/next/src/components/FormMegaLayout/index.tsx, packages/react/src/types.ts
=> fix(layout): type typo

packages/core/src/types.ts
=> feat(core): remove types

docs/zh-cn/jsx-develop/self-inc-component.md, docs/zh-cn/schema-develop/complext-self-inc-component.md, packages/core/src/externals.ts
=> fix: mutator insert

packages/core/src/externals.ts
=> fix(core): fix unmount remove errors

docs/zh-cn/schema-develop/full-express.md, packages/antd/src/components/Button.tsx, packages/antd/src/components/Form.tsx, packages/next/src/components/Button.tsx, packages/next/src/components/Form.tsx, packages/react-schema-renderer/src/components/SchemaForm.tsx
=> feat(antd/next): add stop propagation to form

packages/antd/src/__tests__/__snapshots__/layout.spec.tsx.snap, packages/antd/src/components/FormMegaLayout/ie.tsx, packages/antd/src/components/FormMegaLayout/index.tsx, packages/antd/src/components/FormMegaLayout/style.tsx, packages/next/src/components/FormMegaLayout/index.tsx, packages/react-schema-renderer/src/shared/connect.ts
=> fix: compat ie10-11 for antd3

docs/zh-cn/schema-develop/faq.md, packages/react-schema-renderer/src/shared/expression.ts
=> fix(schema-renderer): Fix expression complie perf bug

packages/antd/src/components/Form.tsx, packages/next/src/components/Form.tsx
=> fix(antd): fix previewPlaceholder errors

packages/react-schema-renderer/src/components/SchemaField.tsx
=> fix(schema-renderer): fix schema field lazy state

packages/antd/README.zh-cn.md, packages/next/README.zh-cn.md
=> doc:完善validate文档

packages/antd/src/components/FormMegaLayout/index.tsx, packages/next/src/components/FormMegaLayout/index.tsx
fix itemStyle not work when wrapped by MegaLayout
=> fix(layout): compat legal props

packages/shared/src/merge.ts
=> fix(shared): Fix merge undefined is not work

packages/antd/src/__tests__/__snapshots__/layout.spec.tsx.snap, packages/antd/src/components/FormMegaLayout/inset.tsx
=> feat: add style lineheight

packages/next/src/components/Form.tsx
=> feat(next): support inline form

packages/antd-components/src/upload/index.tsx, packages/next-components/src/upload/index.tsx
Only fallback to suggested icon with file url when imgURL is not exist.
fix file extension match pattern.
close #1030
=> fix Upload preview image

packages/core/src/externals.ts, packages/react/src/hooks/useField.ts
=> Fix value change trigger order

packages/core/src/shared/model.ts
=> fix(core): fix hasChanged return type

packages/next-components/src/array-table/index.tsx
=> fix(next-components): Replace ArrayList.Item with Table.Column

packages/antd-components/src/date-picker/index.tsx
=> fix(antd-components): fix format nan

packages/antd-components/src/form-step/index.tsx, packages/core/src/__tests__/field.state.spec.ts, packages/core/src/internals.ts, packages/core/src/models/field.ts
=> fix(core): fix form step validate failed

packages/antd/src/components/FormMegaLayout/style.tsx
update megaLayout checkbox alignment
=> feat(layout): update megaLayout checkbox alignment

packages/react-schema-renderer/src/__tests__/registry.spec.tsx, packages/react-schema-renderer/src/components/SchemaField.tsx, packages/react-schema-renderer/src/components/SchemaForm.tsx, packages/react-schema-renderer/src/hooks/useSchemaForm.ts, packages/react-schema-renderer/src/types.ts
add componentPropsInterceptor to make it easier to pass custom props to field/virtual-field
=> feat(react-schema-renderer): add componentPropsInterceptor

packages/antd-components/src/time-picker/index.tsx
=> fix(antd-components): fix timepicker format

packages/antd/src/components/FormItem.tsx
fix [#1053](https://github.com/alibaba/formily/issues/1053)
=> fix: fix form help validate status error

docs/zh-cn/jsx-develop/form-layout.md, packages/antd/src/shared.ts
`antd@4.7.0+`的版本在`Form.Item`组件中新增`tooltip`属性，并且在项目中属于较常用属性
=> feat: add `tooltip` into FormItem`s props

.gitignore, package.json, packages/vue/.eslintrc, packages/vue/.npmignore, packages/vue/README.md, packages/vue/package.json, packages/vue/src/components/ArrayField.vue, packages/vue/src/components/Field.vue, packages/vue/src/components/FormConsumer.vue, packages/vue/src/components/FormProvider.vue, packages/vue/src/components/ObjectField.vue, packages/vue/src/components/ReactiveField.vue, packages/vue/src/components/VoidField.vue, packages/vue/src/components/index.ts, packages/vue/src/global.ts, packages/vue/src/hooks/index.ts, packages/vue/src/hooks/useAttach.ts, packages/vue/src/hooks/useField.ts, packages/vue/src/hooks/useForm.ts, packages/vue/src/hooks/useFormEffects.ts, packages/vue/src/index.ts, packages/vue/src/shared/connect.ts, packages/vue/src/shared/context.ts, packages/vue/src/shared/index.ts, packages/vue/src/shims-vue.d.ts, packages/vue/src/types.ts, packages/vue/src/utils/define-observable-component.ts, packages/vue/tsconfig.json, packages/vue/vue.config.js
Add vue version for Formily2.0.
=> feat(vue): add vue version for Formily2.0

packages/next-components/src/date-picker/index.tsx
=> fix(next): fix month picker

packages/react-schema-renderer/package.json, packages/react-schema-renderer/src/shared/connect.ts
loss statics when wrap with connect hoc
=> fix(react-schema-render): loss statics when wrap with connect hoc

packages/react-schema-renderer/src/__tests__/__snapshots__/markup.spec.tsx.snap, packages/react-schema-renderer/src/__tests__/__snapshots__/register.spec.tsx.snap, packages/react-schema-renderer/src/shared/schema.ts
=> feat(schema): add version tag

package.json, packages/react-logic-diagram/.npmignore, packages/react-logic-diagram/.umirc.js, packages/react-logic-diagram/LICENSE.md, packages/react-logic-diagram/README.md, packages/react-logic-diagram/docs/api.md, packages/react-logic-diagram/docs/index.md, packages/react-logic-diagram/jest.config.js, packages/react-logic-diagram/package.json, packages/react-logic-diagram/rollup.config.js, packages/react-logic-diagram/src/components/Link.tsx, packages/react-logic-diagram/src/components/LogicDiagram.tsx, packages/react-logic-diagram/src/components/index.ts, packages/react-logic-diagram/src/index.ts, packages/react-logic-diagram/src/types.ts, packages/react-logic-diagram/tsconfig.json, scripts/rollup.base.js, yarn.lock
=> feat: add react-logic-diagram component

packages/next/src/logic-diagram/index.tsx
=> fix: use form.setValuesIn instead of field.removeProperty

packages/validator/src/rules.ts
如题：修复 exclusiveMinimum/exclusiveMaximum 书写错误。
=> fix: 修复 exclusiveMinimum/exclusiveMaximum 校验错误

.umirc.js, docs/guide/advanced/build.md
=> docs(project):add build docs

packages/antd/docs/components/Form.md, packages/antd/src/submit/index.tsx
- 去除 antd 的 Form 文档中多余的 import FormProvider
- 导出 Submit 的 props 类型
=> refactor(antd): fine adjustment

packages/reactive-vue/package.json, packages/reactive-vue/src/observer/observerInVue2.ts, packages/reactive/docs/api/vue/observer.md, packages/reactive/docs/api/vue/useObserver.md, packages/vue/docs/.vuepress/config.js, packages/vue/docs/.vuepress/styles/index.styl, packages/vue/docs/api/hooks/useObserver.md, packages/vue/docs/api/shared/Schema.md, packages/vue/docs/api/shared/observer.md
1. Add docs form reactive-vue
2. Fix "export default was not found" error in vue3
=> Feat vue docs

packages/antd/docs/components/Cascader.md, packages/antd/docs/components/FormItem.md, packages/antd/docs/components/Input.md, packages/antd/docs/components/NumberPicker.md, packages/antd/docs/components/Password.md, packages/antd/docs/components/Select.md, packages/antd/docs/components/TreeSelect.md, packages/next/docs/components/Cascader.md, packages/next/docs/components/Input.md, packages/next/docs/components/NumberPicker.md, packages/next/docs/components/Password.md, packages/next/docs/components/Select.md, packages/next/docs/components/TreeSelect.md
=> docs: JOSN -> JSON

packages/reactive/docs/api/markRaw.md, packages/reactive/src/__tests__/annotations.spec.ts
In packages/reactive/
Modify the description of the priority of the marking function in the document
Add test cases for marking functions
=> test(reactive): add mark tests and fix docs typo

packages/reactive/src/__tests__/annotations.spec.ts, packages/reactive/src/__tests__/externals.spec.ts, packages/reactive/src/externals.ts
In packages/reactive
Move externals tests to new file
Fix toJS recursive dependence stack overflow
=> fix(reactive): fix tojs recursive dependence stack overflow

packages/core/docs/api/models/Form.md
=> change a typo

packages/react/src/shared.ts
=> fix: Cannot read property 'getState' of undefined at resolvePayload

packages/antd/src/adaptor/FormItem.tsx, packages/next/src/adaptor/FormItem.tsx
=> fix: description为空字符串时，不显示描述信息元素

packages/antd/src/form-item/style.less
=> fix:修复校验失败后box-shadow依旧为默认主题色的问题

packages/react/README.md
===
Tests not applicable. Scope is docs only.
=> fix(docs): corrected minor typo in documentation

packages/react/docs/api/shared/Schema.md
=> 完善 schema 模块的静态方法使用说明

packages/react-schema-renderer/src/shared/connect.ts
保证组件可以拿到onChange等方法的返回值
eg:
给组件`onChange`传入了一个async函数。
组件内部需要做一些异步的处理，为了保证可以获取`onChange`执行完返回的`Promise`，需要正确返回`onChage`的执行结果
```javascript
const fn=async()=>{
// 等待onChange执行完
await props.onChange()
// do something
}
```
=> feat(react-schema-render): add function return value

.github/PULL_REQUEST_TEMPLATE.md
---
现在用的是有序列表，每次提交 pull request 都要手动改成 `- [x]`，所以想调整下模板。
=> chore: perf github pull request template

packages/antd/src/form-grid/index.tsx, packages/next/src/form-grid/index.tsx
=> feat(antd/next): export FormGrid props interface

packages/validator/src/formats.ts
=> feat:url support /?a=1 and ?a=1

packages/validator/src/formats.ts
=> feat: url regexp support /?a=1 and ?a=1

packages/next/docs/components/index.md
=> fix(doc): next doc

packages/core/src/models/Form.ts
=> fix Form.submit miss return values

packages/core/src/models/Form.ts, packages/core/src/shared/externals.ts, packages/core/src/types.ts
=> add generic type support for createForm

packages/reactive-react/src/index.ts
=> refactor(react-reactive): change the way of observer function pass ref

packages/next/docs/components/FormCollapse.md, packages/next/docs/components/FormDialog.md, packages/next/docs/components/FormDrawer.md, packages/next/docs/components/Password.md, packages/next/docs/components/PreviewText.md, packages/next/docs/components/Upload.md
=> feat(.md): Form => FormLayout

packages/core/src/types.ts
=> refactor(core): modify IFormState type

packages/core/docs/api/models/Form.md, packages/core/src/models/Form.ts, packages/core/src/types.ts
---
最新的 formily_next 分支代码会报错，应该过不了 CI
=> add extra strategy for merge form value

packages/antd/src/form-item/style.less
--- 
small 模式下使用 antd 原始的样式应该就可以：
=> fix(antd): fix btn is too big in small mode

packages/antd/src/form-grid/index.tsx, packages/next/src/form-grid/index.tsx
=> 修复GirdItem gridSpan计算错误

packages/react/src/components/SchemaFieid.tsx
=> fix(react): fix SchemaField missing scope from options

packages/antd/src/form-item/index.tsx, packages/next/src/form-item/index.tsx
=> fix(antd/next): fix FormItem typings

packages/path/src/parser.ts
=> fix(path): fix realative path for sibling in array

packages/next/docs/components/FormDialog.md, packages/next/src/form-dialog/index.tsx
=> feat(next): add fusion context of dialog

packages/antd/src/preview-text/index.tsx, packages/next/src/preview-text/index.tsx
=> refactor(antd/next): refactor PreviewText to JSXComponent

README.md, README.zh-cn.md, packages/core/docs/api/entry/FormValidatorRegistry.md, packages/core/src/shared/externals.ts, packages/next/docs/components/Form.md, packages/next/src/form/index.tsx, packages/validator/src/registry.ts
- feat(next): add fusion multiple lang of validator
- docs(core): add README for contribute
=> feat(next): add fusion multiple lang of validator

packages/antd/package.json, packages/next/package.json
---
Add `sideEffects` in package.json to support rollup tree-shaking feature.
```tsx
// App.tsx
import { Submit } from '@formily/antd'
import React from 'react'
export default (props: any) => {
return (
<div>
<Submit></Submit>
</div>
)
}
```
=> feat(antd/next): add rollup tree-shaking support

packages/core/src/__tests__/field.spec.ts, packages/core/src/models/Field.ts
=> fix(core): fix field value restored incorrectly when hidden toggled

packages/antd/package.json, packages/next/package.json
=> chore(antd/next): revert add rollup tree-shaking support

packages/react/src/__tests__/schema.markup.spec.tsx, packages/react/src/components/RecursionField.tsx
---
https://github.com/alibaba/formily/pull/1462#issuecomment-853655797
=> fix(react): fix SchemaField missing props scope

packages/core/docs/api/entry/FormValidatorRegistry.md, packages/next/README.zh-cn.md, packages/next/src/form/index.tsx, packages/validator/src/registry.ts
Fix the case where the fetch language is empty
doc： setValidationLanguage => setValidateLanguage
=> fix: add defaultLanguage

packages/antd/package.json, packages/next/package.json
=> fix(antd/next): fix dumi lost style due to treeshaking

packages/next/package.json
- [x ] Ensure the test suite passes (`npm test`).
---
#1563 
本地使用 `build:docs` 测试可以了：
=> fix(next): fix style missing due to wrong sideEffects

docs/guide/index.md
Using ‘disgusting’ to describe requirements sounds very unfriendly to product managers and customers
---
Using ‘disgusting’ to describe business requirements sounds very unfriendly to product managers and customers.
=> chore(doc): replace 'disgusting' with 'sophisticated'

packages/vue/src/components/ReactiveField.ts
---
add deep copy to decorator props
=> fix(vue): add deep copy to decorator props

packages/antd/docs/components/Form.md, packages/antd/docs/components/Submit.md, packages/antd/src/form/index.tsx, packages/antd/src/submit/index.tsx, packages/next/docs/components/Form.md, packages/next/docs/components/Submit.md, packages/next/src/form/index.tsx, packages/next/src/submit/index.tsx
=> feat(antd/next): add Form and Submit components submitFailed callback events

packages/core/docs/api/models/Field.md
=> docs: add Type number and integer for ValidatorFormats

packages/antd/src/components/Button.tsx, packages/next/src/components/Button.tsx
---
Add reset button click event
=> fix(component): Add reset button click event

designable/antd/src/components/DesignableArrayTable/index.tsx
=> fix(designable-antd): rename operationNpde to operationNode

packages/json-schema/src/__tests__/transformer.spec.ts, packages/json-schema/src/transformer.ts
---
fix editable invalid
https://codesandbox.io/s/loving-leftpad-ropwn?file=/App.tsx
=> fix(json-schema): fix editable valid

packages/vue/docs/api/shared/schema.md, packages/vue/docs/demos/api/shared/observer.vue, packages/vue/package.json, packages/vue/src/__tests__/field.spec.ts, packages/vue/src/__tests__/form.spec.ts, packages/vue/src/__tests__/schema.json.spec.ts, packages/vue/src/__tests__/schema.markup.spec.ts, packages/vue/src/__tests__/shared.spec.ts, packages/vue/src/components/ArrayField.ts, packages/vue/src/components/Field.ts, packages/vue/src/components/FormConsumer.ts, packages/vue/src/components/FormProvider.ts, packages/vue/src/components/ObjectField.ts, packages/vue/src/components/ReactiveField.ts, packages/vue/src/components/RecursionField.ts, packages/vue/src/components/SchemaField.ts, packages/vue/src/components/VoidField.ts, packages/vue/src/global.d.ts, packages/vue/src/index.ts, packages/vue/src/shared/connect.ts, packages/vue/src/shared/context.ts, packages/vue/src/types/index.ts, packages/vue/src/types/vue-demi.d.ts, packages/vue/src/types/vue2.ts, packages/vue/src/vue2-components.ts, yarn.lock
---
1. add components prop for schema-field
2. support object style of component "style"
3. fix type error
4. add test cases for x-content
=> feat(vue): add components prop for schema-field

packages/core/src/__tests__/field.spec.ts
=> test(core): nested reaction should recall the tracker

.codecov.yml, packages/core/src/__tests__/array.spec.ts, packages/core/src/shared/internals.ts
=> fix(core): fix array exchange with children

packages/core/src/__tests__/form.spec.ts, packages/core/src/models/Form.ts, packages/core/src/shared/internals.ts, packages/reactive/package.json, packages/reactive/src/datatree.ts, packages/reactive/src/global.d.ts, packages/reactive/src/types.ts
=> fix(core): fix lifecycle not working after call form.setXXX

designable/antd/package.json, packages/reactive/src/__tests__/tracker.spec.ts, packages/reactive/src/tracker.ts, packages/reactive/src/untracked.ts
=> fix(reactive): fix Tracker in nested reaction

scripts/release/index.ts
=> build: fix git message sort incorrect

packages/core/src/__tests__/field.spec.ts, packages/core/src/shared/internals.ts, packages/json-schema/src/transformer.ts
=> feat(core): skip validate when parent.visible is equal hidden/none

packages/reactive-react/src/hooks/useForceUpdate.ts, packages/reactive-react/src/hooks/useObserver.ts, packages/reactive-react/src/shared/immediate.ts, packages/reactive/src/tracker.ts
=> fix(reactive): fix Tracker memo leak in StrictMode

packages/react/docs/api/components/ObjectField.md
---
Hardcoding field name `object` in component is bad, take it from context.
=> docs(react): ObjectField

packages/vue/package.json
---
add build:global script to fix vue typing
=> fix(vue): fix vue typing

packages/core/src/__tests__/field.spec.ts, packages/core/src/models/ArrayField.ts, packages/core/src/models/Field.ts, packages/core/src/models/Form.ts, packages/core/src/models/ObjectField.ts, packages/core/src/models/VoidField.ts, packages/core/src/shared/internals.ts, packages/reactive/docs/api/reaction.md, packages/reactive/src/__tests__/annotations.spec.ts, packages/reactive/src/autorun.ts, packages/shared/src/defaults.ts
=> fix(core): fix array value changed but not auto clean node

packages/antd/src/array-table/index.tsx, packages/next/src/array-table/index.tsx
=> fix(antd/next): fix ArrayTable pagination

packages/element/docs/.vuepress/components/dumi-previewer.vue, packages/element/docs/demos/guide/upload.vue, packages/vue/src/components/RecursionField.ts
=> fix(vue): fix x-content is not work with array type

designable/antd/src/components/DesignableArrayCards/index.tsx, designable/antd/src/components/DesignableArrayTable/index.tsx, designable/antd/src/components/DesignableFormCollapse/index.tsx, designable/antd/src/components/DesignableFormTab/index.tsx, designable/antd/src/components/Droppable/index.tsx, designable/antd/src/locales/en-US.ts, designable/antd/src/locales/zh-CN.ts
=> chore(designable-antd): improve locales

packages/element/src/submit/index.ts, scripts/rollup.base.js
---
add rollup element external
=> fix(element): add rollup external to fix element package size

packages/element/docs/demos/guide/cascader/base.vue, packages/element/package.json, yarn.lock
---
fix vuepress doc not identify fetch
=> fix(element): fix vuepress doc not identify fetch

designable/antd/package.json, designable/antd/playground/template.ejs, designable/setters/package.json, designable/setters/src/components/ReactionsSetter/FieldPropertySetter.tsx, designable/setters/src/components/ReactionsSetter/index.tsx, designable/setters/src/components/ReactionsSetter/styles.less, designable/setters/src/locales/en-US.ts, designable/setters/src/locales/zh-CN.ts, packages/core/src/__tests__/form.spec.ts, packages/core/src/shared/internals.ts, yarn.lock
=> fix(core): fix onFormValuesChange does not trigger with ArrayField initialValue

packages/antd/docs/components/FormDialog.md, packages/antd/docs/components/FormDrawer.md, packages/antd/src/form-dialog/index.tsx, packages/antd/src/form-drawer/index.tsx, packages/next/docs/components/FormDialog.md, packages/next/docs/components/FormDrawer.md, packages/next/src/form-dialog/index.tsx, packages/next/src/form-drawer/index.tsx
=> feat(form-dialog): add form dialog and form drawer oncancel return value 

package.json, packages/core/docs/api/models/Form.md, packages/core/src/__tests__/form.spec.ts, packages/core/src/models/Form.ts, scripts/rollup.base.js, yarn.lock
=> feat(project): support bundle dts

packages/vue/docs/api/shared/schema.md, packages/vue/docs/demos/api/components/recursion-field-with-component.vue, packages/vue/docs/demos/api/hooks/use-field.vue, packages/vue/docs/demos/api/hooks/use-form.vue, packages/vue/src/__tests__/field.spec.ts, packages/vue/src/components/ArrayField.ts, packages/vue/src/components/Field.ts, packages/vue/src/components/FormProvider.ts, packages/vue/src/components/ObjectField.ts, packages/vue/src/components/VoidField.ts, packages/vue/src/hooks/useAttach.ts
---
1. fix field doesnt update correctly in designable mode
2. fix doc error
=> fix(vue): fix field doesnt update correctly in designable mode

packages/core/src/__tests__/array.spec.ts, packages/core/src/models/ArrayField.ts, packages/core/src/shared/internals.ts
=> fix(core): fix ArrayField operation will trigger memo leak

packages/next/src/array-table/main.scss
feat(next): optimize array-table validate style
---
=> feat(next): optimize array-table validate style

packages/react/src/shared/connect.ts
=> fix(react): fix select type validate error 

docs/guide/advanced/controlled.md, docs/guide/advanced/controlled.zh-CN.md
=> docs(main): add schema fragment controlled case

packages/element/docs/demos/guide/array-table/effects-markup-schema.vue, packages/element/docs/demos/guide/array-table/markup-schema.vue, packages/element/src/array-base/index.ts, packages/element/src/array-table/index.ts, packages/element/src/array-table/style.scss, packages/element/src/array-table/style.ts, packages/element/src/form-item/index.ts
---
update array-table component & doc
=> feat(element): update array-table component & doc

packages/reactive/src/__tests__/annotations.spec.ts
---
Optimize test case of reactive/box
=> test(reactive): optimize box test case

packages/antd/docs/components/FormDialog.md, packages/antd/docs/components/FormDialog.zh-CN.md, packages/antd/docs/components/FormDrawer.md, packages/antd/docs/components/FormDrawer.zh-CN.md, packages/antd/src/__builtins__/loading.ts, packages/antd/src/form-dialog/index.tsx, packages/antd/src/form-drawer/index.tsx, packages/next/docs/components/FormDialog.md, packages/next/docs/components/FormDialog.zh-CN.md, packages/next/docs/components/FormDrawer.md, packages/next/docs/components/FormDrawer.zh-CN.md, packages/next/src/__builtins__/loading.ts, packages/next/src/form-dialog/index.tsx, packages/next/src/form-drawer/index.tsx
=> feat(antd/next): improve FormDialog/FormDrawer typings and api

designable/antd/src/schemas/Switch.ts
---
reslove antd switch optionType warning
=> fix(designable-antd): remove switch optionType: 'button'

designable/antd/package.json, designable/antd/playground/template.ejs, designable/setters/package.json, devtools/chrome-extension/package.json, packages/core/docs/api/models/Field.md, packages/core/docs/api/models/Field.zh-CN.md, packages/core/docs/api/models/Form.md, packages/core/docs/api/models/Form.zh-CN.md, packages/core/docs/api/models/VoidField.md, packages/core/docs/api/models/VoidField.zh-CN.md, packages/core/src/__tests__/graph.spec.ts, packages/core/src/__tests__/void.spec.ts, packages/core/src/models/Field.ts, packages/core/src/models/Form.ts, packages/core/src/models/VoidField.ts, packages/core/src/shared/internals.ts, yarn.lock
=> feat(core): support field destroy method

packages/antd/src/array-base/index.tsx, packages/element/src/array-base/index.ts, packages/next/src/array-base/index.tsx
=> fix(antd/next/element): fix array base addition default value

packages/next/src/__builtins__/mapStatus.ts, packages/next/src/form-item/index.tsx, packages/next/src/form-item/main.scss
=> fix(next): fix FormItem styles

designable/antd/package.json, designable/setters/package.json, packages/antd/src/form-item/style.less, packages/next/src/form-item/main.scss, yarn.lock
=> fix(antd/next): fix FormItem styles

designable/antd/playground/main.tsx, designable/antd/playground/webpack.base.ts, packages/core/src/__tests__/field.spec.ts, packages/core/src/__tests__/internals.spec.ts, packages/core/src/models/Field.ts, packages/core/src/shared/internals.ts
=> fix(core): fix euqal initial empty value will trigger change

designable/antd/src/components/DesignableField/index.tsx, designable/antd/src/components/DesignableField/options.ts, designable/antd/src/components/DesignableField/types.ts, docs/guide/form-builder.md, docs/guide/form-builder.zh-CN.md
=> feat(designable-antd): support restrictSiblingsComponents

packages/core/src/__tests__/array.spec.ts, packages/core/src/shared/internals.ts
=> fix(core): fix array nested remove

packages/next/src/form-item/scss/variable.scss
=> fix(next): fix node scss error

packages/next/src/__builtins__/hooks/usePrefixCls.ts
=> fix(next): fix config provider prefix bug (#2000)

designable/next/playground/main.tsx, designable/next/src/components/DesignableArrayCards/index.tsx, designable/next/src/components/LoadTemplate/index.tsx, designable/next/src/schemas/Card.ts
---
fix style and support history
=> fix(designable-next): fix style and support history

packages/antd/src/form-item/style.less
=> fix(antd): fix form size=large bug (#1998)

packages/element/docs/demos/guide/time-picker/json-schema.vue, packages/element/docs/demos/guide/time-picker/markup-schema.vue, packages/element/src/array-base/index.ts, packages/element/src/array-cards/index.ts, packages/element/src/array-collapse/index.ts, packages/element/src/array-items/index.ts, packages/element/src/array-table/index.ts
---
fix(element): fix simple array key
docs(element): update TimePicker docs
=> fix(element): fix simple array key

packages/next/src/__builtins__/hooks/usePrefixCls.ts
---
fix when tag is undefined, get next-undfined, expect next-
=> fix(next): fix usePrefixCls tag undefined

docs/guide/advanced/build.md, docs/guide/advanced/build.zh-CN.md
---
In babel7 and later versions, will show errors like this:
to fix this, I update this doc.
=> docs: update Pack on Demand doc

designable/antd/playground/template.ejs
=> fix(designable): fix Uncaught SyntaxError (#1997)

packages/vue/docs/questions/README.md
=> docs(vue): add sloped slot usage description

packages/element/docs/.vuepress/components/createCodeSandBox.js, packages/element/docs/.vuepress/components/dumi-previewer.vue, packages/element/package.json, packages/vue/docs/.vuepress/components/createCodeSandBox.js, packages/vue/docs/.vuepress/components/dumi-previewer.vue, packages/vue/package.json
---
docs(vue/element): add codesandbox support
=> docs(vue/element): add codesandbox support

packages/core/src/__tests__/form.spec.ts, packages/core/src/models/Form.ts, packages/core/src/shared/internals.ts
=> fix(core): fix initialValues patch values with wrong type

packages/vue/src/shared/fragment.ts, packages/vue/src/shared/h.ts
---
fix(vue): fix vue2 scopedSlot and slot pass problem
=> fix(vue): fix vue2 scopedSlot and slot pass problem

packages/vue/docs/demos/questions/scoped-slot.vue, packages/vue/docs/questions/README.md, packages/vue/src/__tests__/schema.json.spec.ts
---
add tests and some readme document for #2221
=> docs(vue): add more scopedSlot content tests and readme

packages/element/package.json, packages/element/src/array-cards/index.ts, packages/element/src/array-collapse/index.ts, packages/element/src/array-tabs/index.ts, packages/element/src/editable/index.ts, packages/element/src/form-collapse/index.ts, packages/element/src/form-dialog/index.ts, packages/element/src/form-drawer/index.ts, packages/element/src/form-item/index.ts, packages/element/src/form-tab/index.ts, packages/vue/src/shared/fragment.ts, packages/vue/src/shared/h.ts
---
refactor(element): refactor element slot pass way
=> refactor(element): refactor element slot pass way

packages/element/docs/demos/guide/form.vue, packages/element/src/array-items/index.ts, packages/element/src/form/index.ts
---
fix(element): fix form props pass bug
=> fix(element): fix form props pass bug

packages/core/src/__tests__/field.spec.ts, packages/core/src/models/Field.ts, packages/core/src/models/VoidField.ts, packages/core/src/shared/constants.ts, packages/core/src/shared/internals.ts, packages/json-schema/src/__tests__/server-validate.spec.ts, packages/json-schema/src/__tests__/traverse.spec.ts, packages/json-schema/src/shared.ts, packages/json-schema/src/transformer.ts, packages/react/src/components/RecursionField.tsx, packages/reactive/docs/api/batch.md, packages/reactive/docs/api/batch.zh-CN.md, packages/reactive/src/__tests__/batch.spec.ts, packages/reactive/src/array.ts, packages/reactive/src/batch.ts, packages/reactive/src/environment.ts, packages/reactive/src/reaction.ts, packages/reactive/src/types.ts
=> fix(core): fix reactions initial value will overwrite value

packages/core/src/models/BaseField.ts, packages/core/src/models/Field.ts, packages/core/src/models/Query.ts, packages/core/src/models/VoidField.ts
=> refactor(core): reduce core package size

packages/core/src/__tests__/form.spec.ts, packages/core/src/models/Field.ts, packages/core/src/shared/internals.ts
=> fix(core): fix validate skip

packages/json-schema/src/transformer.ts, packages/path/src/index.ts, packages/react/src/components/SchemaField.tsx, packages/reactive/src/__tests__/batch.spec.ts, packages/reactive/src/internals.ts, scripts/jest.base.js, tsconfig.jest.json
=> fix(reactive): fix batch api can not throw error

packages/vue/src/__tests__/field.spec.ts, packages/vue/src/components/ReactiveField.ts
=> fix: fix decorator attrs is not passed down correctly

packages/antd/src/array-table/index.tsx, packages/antd/src/array-table/style.less, packages/next/src/array-table/index.tsx, packages/next/src/array-table/main.scss
=> chore(antd/next): improve array table ui

packages/core/src/__tests__/field.spec.ts, packages/core/src/__tests__/form.spec.ts, packages/core/src/models/Field.ts, packages/core/src/shared/internals.ts
---
About https://github.com/alibaba/formily/discussions/2372
=> refactor(core): revert field unmount to skip validate

docs/guide/advanced/layout.md, docs/guide/advanced/layout.zh-CN.md, docs/guide/scenes/dialog-drawer.md, docs/guide/scenes/dialog-drawer.zh-CN.md, docs/guide/scenes/step-form.zh-CN.md, docs/guide/scenes/tab-form.md, docs/guide/scenes/tab-form.zh-CN.md
=> docs: fix scenes url

packages/reactive/src/__tests__/annotations.spec.ts, packages/reactive/src/__tests__/autorun.spec.ts, packages/reactive/src/__tests__/tracker.spec.ts, packages/reactive/src/annotations/computed.ts, packages/reactive/src/tracker.ts
=> fix(reactive): fix computed/tracker did not recollect dependencies

packages/core/src/shared/internals.ts, packages/core/src/types.ts
=> fix(core): fix reset should clear field caches

packages/grid/src/index.ts
=> fix(grid): fix grid calculate failed when container was hidden

packages/antd/docs/components/FormGrid.md, packages/antd/docs/components/FormGrid.zh-CN.md, packages/element/docs/guide/form-grid.md, packages/grid/src/index.ts, packages/next/docs/components/FormGrid.md, packages/next/docs/components/FormGrid.zh-CN.md
=> feat(grid): add strictAutoFit option

packages/core/docs/api/models/Form.zh-CN.md
---
Form model中文文档中的链接目前是跳转到英文链接的，pr修改为跳转到对应的中文链接
=> docs(core): update links in Form model Chinese doc

packages/grid/package.json
---
Fix build issue for grid package.
=> fix(grid): fix build by removing build:global

packages/grid/src/index.ts, packages/grid/src/observer.ts, yarn.lock
=> fix(grid): fix grid can not observe data-grid-span

docs/guide/advanced/async.zh-CN.md, docs/guide/advanced/business-logic.zh-CN.md, docs/guide/advanced/controlled.zh-CN.md, docs/guide/advanced/custom.zh-CN.md, docs/guide/advanced/layout.zh-CN.md, docs/guide/advanced/linkages.zh-CN.md, docs/guide/advanced/validate.zh-CN.md, docs/guide/index.zh-CN.md, docs/guide/quick-start.zh-CN.md, docs/guide/scenes/dialog-drawer.zh-CN.md, docs/guide/scenes/step-form.zh-CN.md, docs/guide/scenes/tab-form.zh-CN.md, docs/guide/upgrade.zh-CN.md
=> docs: update links of Chinese guide docs

packages/antd/src/upload/index.tsx, packages/next/src/upload/index.tsx
---
由于三元表达式的优先级低于或运算[https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence#table](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence#table)
该问题会导致target存在`errorMessage`，`errMsg`，`errorMsg`时都会使用`target.error || ''`作为返回值，应该是不符合预期的。
=> fix: fix validator notify error message of Antd Upload Item

packages/core/src/shared/internals.ts, packages/core/src/types.ts, packages/validator/src/parser.ts
=> chore: improve validator context

packages/element/src/form-layout/index.ts, packages/reactive-vue/src/hooks/useObserver.ts, packages/reactive-vue/src/observer/observerInVue3.ts
=> fix(element): fix FormLayout provide props not update 

packages/core/docs/api/models/Field.md, packages/core/docs/api/models/Field.zh-CN.md, packages/core/src/__tests__/field.spec.ts, packages/core/src/models/Field.ts, packages/core/src/shared/internals.ts
=> feat(core): add selfModified to field model

packages/grid/src/index.ts
=> fix(grid): fix calc origin columns

packages/core/docs/api/models/Field.md, packages/core/docs/api/models/Field.zh-CN.md, packages/core/docs/api/models/VoidField.md, packages/core/docs/api/models/VoidField.zh-CN.md, packages/core/src/__tests__/field.spec.ts, packages/core/src/models/BaseField.ts, packages/core/src/models/Field.ts, packages/core/src/models/VoidField.ts
---
add setData & setContent of field models
=> feat(core): add setData & setContent of field models

packages/element/src/array-base/index.ts, packages/element/src/array-collapse/index.ts
=> fix(element): fix vue list key not update correctly

packages/antd/docs/components/FormGrid.md, packages/antd/docs/components/FormGrid.zh-CN.md, packages/antd/src/form-grid/index.tsx, packages/grid/src/index.ts, packages/next/docs/components/FormGrid.md, packages/next/docs/components/FormGrid.zh-CN.md, packages/next/src/form-grid/index.tsx
=> feat(antd/next): support createFormGrid api

packages/reactive/src/__tests__/autorun.spec.ts, packages/reactive/src/handlers.ts, packages/reactive/src/reaction.ts
=> fix(reactive): fix the incomplete coverage of runReactions batch mode

packages/element/docs/.vuepress/components/dumi-previewer.vue, packages/element/docs/.vuepress/config.js, packages/element/docs/demos/guide/form-grid/form.vue, packages/element/docs/guide/form-grid.md, packages/element/docs/guide/index.md, packages/element/package.json, packages/element/src/form-grid/index.ts, packages/element/src/form-item/style.scss
=> feat(element): support createFormGrid api

packages/core/src/__tests__/field.spec.ts, packages/core/src/__tests__/form.spec.ts, packages/core/src/shared/internals.ts, packages/validator/src/__tests__/validator.spec.ts, packages/validator/src/parser.ts
=> fix(core): fix required validate with wrong order

.umirc.js
=> docs: update Chinese guide 1.x link

packages/element/package.json
=> chore(element): update ts-import-plugin version

packages/element/src/form-item/index.ts
FormItem's container may not contain a label element which leads to an error
- [x ] Ensure the pull request title and commit message follow the [Commit Specific](https://github.com/alibaba/formily/blob/formily_next/.github/GIT_COMMIT_SPECIFIC.md) in **English**.
- [x ] Fork the repo and create your branch from `master` or `formily_next`.
- [x ] Make sure your code lints (`npm run lint`) - we've done our best to make sure these rules match our internal linting guidelines.
---
add optional chaining
=> fix(element): FormItem useOverflow hook

packages/reactive/src/__tests__/tracker.spec.ts, packages/reactive/src/annotations/computed.ts, packages/reactive/src/array.ts, packages/reactive/src/tracker.ts
---
FIxed https://github.com/alibaba/formily/discussions/2494
=> fix(reactive): fix tracker unexpect update with strict-mode

packages/next/src/space/index.tsx
- [] If you've added code that should be tested, add tests!
---
Fixed #2527
=> fix(next): fix Space align is not work

packages/react/src/__tests__/schema.markup.spec.tsx, packages/react/src/components/RecursionField.tsx
=> fix(react): fix void field props.children is not undefined

packages/antd/src/form-layout/useResponsiveFormLayout.ts, packages/element/src/form-layout/useResponsiveFormLayout.ts, packages/next/src/form-layout/useResponsiveFormLayout.ts
=> fix(next/antd/vue): fix useResponsiveFormLayout props for tooltipIcon bug

packages/vue/src/__tests__/schema.markup.spec.ts, packages/vue/src/components/RecursionField.ts
=> fix(vue): fix void field children is not undefined

packages/json-schema/src/transformer.ts, packages/json-schema/src/types.ts, packages/react/src/__tests__/schema.markup.spec.tsx
=> fix(json-schema): fix  target is null in runner script

packages/core/src/__tests__/field.spec.ts, packages/reactive/src/autorun.ts
=> fix(reactive): fix unexpect effect in reactions

packages/antd/.umirc.js, packages/core/.umirc.js, packages/next/.umirc.js, packages/react/.umirc.js, packages/reactive/.umirc.js
=> docs: site show brandName

packages/antd/src/form-item/index.tsx, packages/antd/src/form-layout/index.tsx, packages/antd/src/form-layout/useResponsiveFormLayout.ts, packages/core/src/__tests__/field.spec.ts, packages/core/src/models/Field.ts, packages/core/src/shared/internals.ts, packages/next/src/form-item/index.tsx, packages/next/src/form-layout/index.tsx, packages/next/src/form-layout/useResponsiveFormLayout.ts, packages/react/src/__tests__/schema.markup.spec.tsx, packages/react/src/components/ReactiveField.tsx, packages/reactive/src/__tests__/annotations.spec.ts, packages/reactive/src/__tests__/observe.spec.ts, packages/reactive/src/annotations/computed.ts, packages/reactive/src/annotations/ref.ts, packages/reactive/src/externals.ts, packages/reactive/src/internals.ts, packages/reactive/src/observe.ts, packages/reactive/src/tree.ts, packages/validator/src/__tests__/parser.spec.ts, packages/validator/src/parser.ts
=> perf: improve total performance 20%

packages/json-schema/src/transformer.ts, packages/react/src/__tests__/schema.markup.spec.tsx
---
修复x-reactions多个响应器存在时会相互影响的问题
=> fix(json-schema): fix x-reactions will affect each other when multiple reactions

packages/antd/src/form-item/style.ts, packages/core/src/__tests__/field.spec.ts, packages/core/src/models/Field.ts, packages/next/docs/components/ArrayCollapse.zh-CN.md, packages/next/docs/components/ArrayItems.zh-CN.md, packages/next/src/array-collapse/index.tsx
=> fix(antd/next): fix components behaviors

packages/vue/src/__tests__/schema.markup.spec.ts, packages/vue/src/components/ReactiveField.ts
---
fix x-content not work in void field
=> fix(vue): fix x-content not work in void field

packages/element/docs/.vuepress/components/createCodeSandBox.js, packages/element/docs/.vuepress/config.js, packages/element/docs/.vuepress/styles/index.styl, packages/element/docs/README.md, packages/element/src/form-item/index.ts
=> docs(element): update element brandName & codesandbox

packages/vue/src/__tests__/utils.spec.ts, packages/vue/src/shared/h.ts, packages/vue/src/utils/formatVNodeData.ts
=> fix(vue): fix format vue3 h function props

packages/core/docs/api/models/ArrayField.md, packages/core/docs/api/models/ArrayField.zh-CN.md
---
core 文档 `Prommise` -> `Promise`
=> docs(core): fix typo

packages/element/src/preview-text/index.ts
---
fix(element): fix usePlaceholder not update error
=> fix(element): fix usePlaceholder not update error

packages/core/src/__tests__/field.spec.ts, packages/core/src/shared/internals.ts
=> fix(core): fix setValues is not work when called reset

packages/element/src/preview-text/index.ts
=> fix(element): fix usePlaceholder value empty error

packages/vue/src/__tests__/schema.json.spec.ts, packages/vue/src/components/ReactiveField.ts
---
improve performance of formily/vue
=> feat(vue): improve performance of formily/vue

packages/core/docs/api/entry/FormValidatorRegistry.md, packages/core/docs/api/entry/FormValidatorRegistry.zh-CN.md
---
Update `setValidationLanguage` to `setValidateLanguage` in doc.
=> docs(core): update setValidationLanguage to setValidateLanguage

packages/reactive-vue/src/hooks/useObserver.ts
=> fix(reactive-vue): fix #2655

packages/reactive-vue/src/__tests__/observer.spec.ts, packages/reactive-vue/src/hooks/useObserver.ts, packages/reactive-vue/src/observer/index.ts, packages/reactive-vue/src/observer/observerInVue2.ts, packages/reactive-vue/src/observer/observerInVue3.ts, packages/reactive-vue/src/types.ts, packages/reactive/docs/api/vue/observer.md, packages/reactive/docs/api/vue/observer.zh-CN.md
=> feat(reactive-vue): add observer option scheduler

packages/element/src/__builtins__/shared/transform-component.ts, packages/element/src/array-items/index.ts, packages/element/src/array-table/index.ts, packages/element/src/array-tabs/index.ts, packages/element/src/form-item/index.ts
=> feat(element): improve performance of ArrayTable

packages/path/README.md
Revision description
---
Revision description
=> fix(path): update README.md

devtools/chrome-extension/src/app/index.tsx, devtools/chrome-extension/src/extension/backend.ts
---
当在devtools中选中节点时,自动在chrome的devtools中绑定$vm
=> feat(devtools): devtools选中节点树时支持console中绑定$vm

packages/vue/scripts/switch-cli.js, packages/vue/scripts/utils.js
=> fix(vue): fix postinstall error

.umirc.js
---
add @formily/antdv doc link
=> feat(docs): add antdv doc link

.github/CONTRIBUTING.md, .github/PULL_REQUEST_TEMPLATE.md
---
change pr template and commit message specific link， avoid 404.
=> chore: change pr template and commit message specific link

packages/antd/src/array-base/index.tsx, packages/next/src/array-base/index.tsx
=> feat(next/antd): support disabled props from field in ArrayBase.Addition

packages/element/src/array-table/index.ts
=> fix(element): fix ArrayTable index error

packages/element/docs/demos/guide/array-table/markup-schema.vue, packages/element/src/array-table/style.scss
=> fix(element): fix ArrayTable style error

packages/core/docs/api/models/Field.md, packages/core/docs/api/models/Field.zh-CN.md, packages/core/src/__tests__/array.spec.ts, packages/core/src/__tests__/field.spec.ts, packages/core/src/models/BaseField.ts, packages/core/src/models/Field.ts, packages/core/src/models/VoidField.ts, packages/core/src/shared/internals.ts
---
考虑到很多数组场景需要消费字段的索引，所以直接挂到字段模型上去
=> feat(core): support index/indexes properties

packages/core/src/__tests__/field.spec.ts, packages/core/src/models/Field.ts
=> fix(core): fix nest visible defualt value is not work

packages/validator/src/formats.ts
=> fix(validator): correct indian rupee regexp

packages/antd/src/array-tabs/index.tsx
=> fix(antd): fix ArrayTabs auto switch activeKey

packages/core/src/__tests__/array.spec.ts, packages/core/src/shared/internals.ts
=> fix(core): fix reset can not clear value in array list

packages/react-shared-components/src/DragListView.tsx
---
change props **handlerSelector** to **handleSelector** in ReactDragListView Component
[ReactDragListView](https://github.com/raisezhang/react-drag-listview) doesn't have props **handlerSelector** in its API, so it is an error props. And according to its API table, **handleSelector** is the right property.
=> fix(react-shared-components): fix build error

packages/core/docs/api/models/Field.zh-CN.md
=> docs: fix a typo in Field.zh-CN.md

packages/shared/src/__tests__/index.spec.ts, packages/shared/src/merge.ts
=> fix(shared): fix set values will merge moment object

packages/shared/src/__tests__/index.spec.ts, packages/shared/src/merge.ts
=> fix(shared): fix merge empty object is not work

packages/core/src/__tests__/field.spec.ts, packages/core/src/models/Query.ts, packages/core/src/shared/internals.ts, packages/path/src/index.ts, packages/path/src/parser.ts
=> fix(core): fix relative match can not skip void field

.umirc.js
=> docs: add vant link

packages/antd/src/upload/index.tsx, packages/next/src/upload/index.tsx
=> fix(antd/next): fix upload typings

packages/json-schema/src/transformer.ts, packages/json-schema/src/types.ts
=> feat(json-schema): support read scope in x-reactions

packages/path/src/index.ts, packages/reactive/src/handlers.ts
=> chore: improve performance

packages/core/src/__tests__/lifecycle.spec.ts
=> test(code): optimize test case of core/lifecycle

packages/reactive-vue/src/hooks/useObserver.ts
=> fix(reactive-vue): fix form whole tree rerendered when value changed in vue3

.umirc.js
=> feat: add Component Ecology: semi

packages/vue/src/__tests__/form.spec.ts, packages/vue/src/components/FormConsumer.ts, packages/vue/src/vue2-components.ts
---
Fix FormConsumer not updates correctly.
This problem occurs when Field's `display` changed from 'visible' to 'none', `form.values` won't change in view.
=> fix(vue): fix FormConsumer not updates correctly

packages/next/src/date-picker/index.tsx, packages/next/src/date-picker2/index.tsx
=> fix(next): datepicker2 and datepicker format

packages/antd/src/__builtins__/portal.tsx, packages/next/src/__builtins__/portal.tsx
---
修复FormDialog FormDrawer 在有Portal包裹下，关闭弹窗后 root div 没有清除的问题
=> fix(antd/next): remove host element after unmount in portal

packages/vue/src/shared/connect.ts
---
Improve performance of mapProps.
=> feat(vue): improve performance of mapProps

packages/grid/src/index.ts
=> fix(grid): fix grid calculate

packages/reactive-vue/src/hooks/useObserver.ts
=> perf(reactive-vue): optimize vue3 tracker performance consumption of multiple instances

packages/next/src/select-table/index.tsx, packages/next/src/select-table/useCheckSlackly.tsx, packages/next/src/select-table/useTitleAddon.tsx
=> fix(next): fix selected bug by search in SelectTable

packages/next/src/select-table/index.tsx, packages/next/src/select-table/useCheckSlackly.tsx, packages/next/src/select-table/useFilterOptions.tsx, packages/next/src/select-table/useTitleAddon.tsx, packages/next/src/select-table/utils.ts
=> fix(next): fix selected bug2 by search in SelectTable

packages/validator/src/__tests__/validator.spec.ts, packages/validator/src/rules.ts
=> fix(validator): fix unexpect validate with empty format

packages/grid/src/index.ts
=> fix(grid): fix grid mutation observer infinite loop

packages/antd/docs/components/SelectTable.md, packages/antd/docs/components/SelectTable.zh-CN.md, packages/antd/src/select-table/index.tsx, packages/next/docs/components/SelectTable.md, packages/next/docs/components/SelectTable.zh-CN.md, packages/next/src/select-table/index.tsx
=> fix(next/antd): fix Pure JSX bug in SelectTable

packages/antd/src/select-table/useFilterOptions.tsx, packages/next/src/select-table/useFilterOptions.tsx
=> fix(antd/next): fix null in dataSource error in SelectTable

packages/antd/src/__builtins__/hooks/usePrefixCls.ts
=> fix(antd): fix ConfigProvider.ConfigContext error in antd@4.6.3-

packages/core/src/__tests__/externals.spec.ts, packages/core/src/__tests__/field.spec.ts, packages/core/src/shared/internals.ts, packages/path/src/__tests__/accessor.spec.ts, packages/path/src/index.ts, packages/shared/src/isEmpty.ts
---
修复 initialValues=null 赋值失效，与 reset initialValues=null 失效的问题
=> fix(core): fix initialValue=null and reset null invalid bug (#2932)

packages/antd/src/array-tabs/index.tsx, packages/core/src/models/Field.ts
=> fix(antd): fix array tabs error badges

packages/reactive/src/__tests__/observable.spec.ts, packages/reactive/src/__tests__/observe.spec.ts, packages/reactive/src/internals.ts
---
针对动态构建的observable树，如果一个临时节点，之前没有父节点，挂载到一个节点上，那么就认定该节点为父节点，不可取消
Close #2950
=> feat(reactive): support observe dynamic tree

packages/reactive-vue/src/hooks/useObserver.ts
=> fix(reactive-vue): fix the exception of multiple update nodes in vue3 case

packages/antd/src/preview-text/index.tsx, packages/next/src/preview-text/index.tsx
=> fix(antd/next): fix PreviewText.Cascader bug

docs/guide/issue-helper.md, docs/guide/issue-helper.zh-CN.md
---
Update codesandbox links of the issue-helper.
=> docs: update codesandbox templates that use the latest formily

packages/antd/src/form-step/index.tsx
---
To fix ts check issue of Step Form, please refer to the pic below
=> fix(antd): StepPane & createFormStep should not be optional property

docs/guide/advanced/controlled.md, docs/guide/advanced/controlled.zh-CN.md, packages/antd/src/array-base/index.tsx, packages/antd/src/form-step/index.tsx, packages/core/src/__tests__/array.spec.ts, packages/core/src/__tests__/field.spec.ts, packages/core/src/shared/internals.ts, packages/next/src/array-base/index.tsx, packages/next/src/form-step/index.tsx
---
Fixed #2971 
Fixed #2976 
Fixed #2983
=> fix: fix destroy can not remove value/initialValues and FormStep reactive strategy

packages/antd/src/array-base/index.tsx, packages/next/src/array-base/index.tsx
---
fix type `ArrayBaseMixins`
=> fix(next/antd): fix array base type

packages/core/src/__tests__/form.spec.ts, packages/core/src/models/BaseField.ts, packages/core/src/models/Form.ts
=> fix(core): fix form unmount should not clear values

packages/antd/src/preview-text/index.tsx, packages/next/src/preview-text/index.tsx
=> fix(antd/next): fix cascader preview text exception errors

packages/antd/src/form-step/index.tsx, packages/next/src/form-step/index.tsx
=> fix(antd/next): fix form step next validate can not prevent custom errors

packages/antd/src/preview-text/index.tsx
=> fix(antd): fix error, can't read 'length' of undefined (#3020)

packages/antd/src/form-tab/index.tsx, packages/next/src/form-tab/index.tsx
---
change FormTab type to fix undefined issue
=> fix(antd): fix form tab type check issue

packages/antd/src/array-collapse/style.ts
=> fix(antd/next): fix array-collapse badge no style

packages/next/src/date-picker/index.tsx
---
next component: date-picker
=> fix(next): fix date time picker value format

packages/element/src/array-base/index.ts, packages/element/src/checkbox/index.ts, packages/element/src/form-dialog/index.ts, packages/element/src/form-drawer/index.ts
=> fix(element): fix FormDialog/FormDrawer promise status error

packages/antd/create-style.ts, packages/next/create-style.ts, packages/next/src/main.scss
=> feat(antd/next): add style generator

packages/core/src/__tests__/array.spec.ts, packages/core/src/shared/internals.ts
=> fix(core): fix array child reactions invalid with remove

packages/antd/docs/components/SelectTable.md, packages/antd/docs/components/SelectTable.zh-CN.md, packages/antd/src/select-table/index.tsx
---
fix the problem that when optionAsValue, the value is lost when searched or paged
=> fix(antd): fix the problem that when optionAsValue, the value is lost when searched or paged
