alibaba/formily

- docs/API/Field_React.md
之前的写法有问题 
`Object | Array <String | Object | Function> | String | Function`
sort-api-table 脚本执行后以为 `| ` 是列的分隔符.
> docs: remove useless column in field api table

- packages/utils/src/__tests__/index.spec.js
- packages/utils/src/array.js
修改了utils中every和some的代码，使其在传入空数组的时候，表现能与JavaScript原生的every、some一致。
另外添加了一些测试用例。
> fix(@uform/utils): fix bug of every and some

- packages/core/src/field.js
问题：#113
方案：
对于值缓存，策略主要是：
1. 如果是visible为false的是默认会缓存值
2. 如果是显示删除具体值的情况，是不会缓存任何值的，比如Array List场景，点击删除某一行的数据
> fix(@uform/core): Fixed the value was not cached when the field was hidden

- docs/Examples/antd/Relations.md
- packages/core/src/index.js
因为onFieldChange会提前触发，用于解决默认联动的问题，但是对于默认联动存在一个顺序问题，要理清顺序问题就得理清联动的关系：
- 相邻字段联动
- 父子字段联动
- 相邻跨父联动
然后我们再论证一下每种联动方式是否会受顺序改变而影响
- 相邻字段联动，如果是A,B,C三个字段，A变化会控制B的状态，C变化也会控制B的状态，如果是控制B的相同状态属性，那就会存在一个顺序+优先级问题，应该是C优先级高还是A优先级高，这个我们以正常命令式程序的后序优先的执行策略即可，也比较符合人类思维
- 相邻跨父联动，其实核心还是相邻字段联动，所以还是以后序优先策略来就行了
- 父子字段联动，这个为啥是最后才讲，主要是因为它很复杂，因为父子字段联动是存在隐式联动的，具体就是：
- 改变父字段的visible状态会影响子字段的visible状态，但改变子字段的visible状态不会影响父字段的visible状态
- 改变父字段的value/initialValue会影响子字段的value/initialValue，同时改变子字段的value/initialValue也会改变父字段的value/initialValue
总结下来，父子之间的隐式关联在于 **存在性状态+值状态**
然后，我们再继续梳理
- visible状态是否会受顺序所影响，很明显，如果A是父，B是子，C是B的相邻字段或者跨父相邻字段，如果A与C都对B的visible状态做控制，我们可以看看，如果按照后序优先的原则来处理会不会出现问题，首先我们需要将父子关系打扁，形成一个顺序型结构，打扁后的顺序结构是按照节点遍历的顺序来生成的，相当于子节点是后序节点，参考css层叠样式表的优先级规则，父级规则会被子级规则所覆盖，所以，如果C是A的子节点，那么优先级会比A高，会覆盖A的控制，没问题，如果C是A的先序相邻节点，那么A的优先 …
> fix(@uform/core): fix initial onFieldChange trverse order

- packages/core/src/form.ts
- packages/react/src/shared/context.tsx
- packages/react/src/state/field.tsx
- packages/react/src/state/form.tsx
- packages/react/src/type.ts
- packages/types/src/form.ts
- packages/utils/src/clone.ts
> feat(@uform/types): improve types

- docs/API/Submit.md
- packages/antd/src/components/button.tsx
- packages/antd/src/components/layout.tsx
- packages/antd/src/types/components/button.d.ts
- packages/antd/src/types/components/layout.d.ts
修正 `FormLayout`、`Submit` 组件的类型声明
Close #181
> fix(typings): correction FormLayout、Submit typings

- packages/core/src/utils.ts
- packages/react/src/__tests__/actions.spec.js
- packages/react/src/__tests__/value.spec.js
```
setFormState(state=>{
state.values.aa = 123
})
```
这种操作不生效，原因是操作执行前是浅拷贝，导致引用一样，判断相等失败
> fix(@uform/core): fix setFormState is not work

- packages/react/src/__tests__/value.spec.js
- packages/react/src/state/form.tsx
Fix #190 
修复方式，主要是去掉了StateForm的shouldUpdate判断，这部分是没有必要的，之前加上它是因为在StateForm的onFormChangeHandler方法内执行了setState，onFormChangeHandler触发时机是@uform/core的formNotify方法执行的时候触发，就是说每次字段变化都会触发，其实，form级别的状态，只需要引用是管理即可。
同时，顺带修复了受控改变initialValues的时候，重置可能无法回滚到最新的intialValues状态
> fix(@uform/core/react): Fix intialValues can not one way controlled

- packages/antd/package.json
- packages/next/package.json
因为按需加载antd/next功能有问题，所以暂时还是使用tsc来编译@uform/antd和@uform/next
> fix: revert import antd/next on demand

- docs/Examples/antd/Validation.md
- packages/antd/src/fields/password.tsx
field password 增加 size prop 的接收，跟其他的 field 组件保持一致的表现，不然在外层的 FormLayout 定义了 `size="large"` ，password 会因为没有接收到该值而导致没有预期的表现
调整 `.ant-input-suffix` 的样式，避免在设置了 `prefix` 的时候，导致点击输入的热区被遮挡了一部分，使得点击输入困难
另外 antd 已经新增了 [password-input](https://ant.design/components/input-cn/#components-input-demo-password-input) 组件，是否可以考虑下将 password-field 交由 antd 原生实现？
> fix(@uform/antd): password add size props

- packages/react/src/__tests__/virtualbox.spec.js
- packages/react/src/state/field.tsx
原因是Field创建之后，它的schema属性就和主schema脱节了，因为它需要作为FieldState的一部分，所以schema与其子节点的关系就无法维系了，只能手动在渲染过程中将其重新建立关联。解决方案不太优雅，但是可以实际解决问题，后续在重构@uform/core的时候需要核心考虑schema关系的管理，因为uform经过这么长的实践探索之后，发现@uform/core其实是一个面向JSON Schema的观察者表单管理模型，所以后续在重构的过程中，@uform/core内部将会拥有完备的schema管理能力
Fix #217
> fix(@uform/react): fix schema properties can not update when rerender

- packages/core/src/field.ts
- packages/react/src/__tests__/effects.spec.js
- packages/react/src/__tests__/value.spec.js
Fix #213 
过滤第一次onFieldChange的最佳方案可以参考测试用例，对pristine做过滤
> fix(@uform/core): fix value can't be remove in onFieldChange subscriber

- packages/react/src/__tests__/validate.spec.js
- packages/validator/src/index.ts
Fix #230 
问题原因：field.lastValidateValue默认是undefiend，同时只有第一次校验完了之后才会被赋值，所以就存在undefiend和空字符串不一致导致进入校验流程，所以需要加一个空值检查，如果两个都是空值，就不用判断相等了
> fix(@uform/validator): Fix validate threshold check

- packages/antd/src/fields/date.tsx
周组件不可用，主要是时间格式转换上有问题，后续对于新增组件的PR，必须要求本地文档跑通才能merge
> fix(@uform/antd): fix week type format

- packages/core/src/utils.ts
增加向后兼容逻辑，很hack，0.13.x以下的版本是不存在unstable_requestPaint这个API的，所以用这个来检测
> fix(@uform/core): add scheduler backward compat

- packages/antd/src/fields/upload.tsx
antd upload 升级之后Dragger组件不允许传children了，只能干掉children，否则文档构建会报错
> fix(@uform/antd): fix antd upload types

- docs/Examples/antd/International.md
- docs/Examples/antd/Sample.md
- packages/antd/src/fields/date.tsx
支持更多format属性的设定，比如 `format: 'gggg-w周'`、`format: 'gggg年 第w周 '`等
> fix(antd): improve week type moment parse regex

- packages/core/src/__test__/form.spec.js
- packages/core/src/field.ts
- packages/react/src/__tests__/schema_form.spec.js
close #263 
增加对 field 的 lastValidateValue 属性在有 initialValue 值的时候，进行对应赋值，避免在初次键入时，执行的 runValidation 中，values 的值是有该 field 的 initialValue 值，而 lastValidateValue 则为 undefined，从而导致了不必要的校验
> fix(core): Increase lastValidateValue value processing during initialization

- packages/antd/src/type.tsx
- packages/next/src/type.tsx
补全 IFormButtonGroupProps 缺失的 align 定义
> fix: ButtonGroup missing the definition of align prop

- package.json
- packages/antd/src/utils.tsx
- packages/next/src/utils.tsx
详情模式下的文本匹配之前采用的强等匹配，这个实在太严格了，对于后端接口来说，很难满足强等
> Fix text equal

- packages/antd/README.md
- packages/antd/README.zh-cn.md
- packages/next/README.md
- packages/next/README.zh-cn.md
- packages/printer/src/index.js
1. 修复文档printer展示问题
2. 增加getFormSchema的interface到文档中
> fix(@uform/printer): change getSchema to get FormSchema

- package.json
- packages/antd/README.md
- packages/antd/README.zh-cn.md
- packages/core/README.md
- packages/core/README.zh-cn.md
- packages/core/src/__tests__/index.spec.ts
- packages/core/src/index.ts
- packages/core/src/types.ts
- packages/next/README.md
- packages/next/README.zh-cn.md
- packages/next/src/components/Button.tsx
- packages/react-schema-renderer/src/__tests__/effects.spec.tsx
- packages/react-schema-renderer/src/__tests__/validate.spec.tsx
- packages/react/README.md
- packages/react/README.zh-cn.md
- packages/react/src/__tests__/actions.spec.tsx
- packages/react/src/__tests__/useForceUpdate.spec.tsx
- packages/react/src/hooks/useField.ts
优化validate的逻辑，错误立即退出(reject), submit以及相关单测也做变化
> fix(@uform/core): validate

- packages/antd/src/types.ts
- packages/next/src/types.ts
由于使用联合类型 & 会导致同名成员变量也根据 & 叠加，因此针对onSubmit用omit来提取
```typescript
type Omit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>
```
> fix(@uform/antd/next): onSubmit type merge error

- packages/antd/README.md
- packages/antd/README.zh-cn.md
- packages/next/README.md
- packages/next/README.zh-cn.md
> fix(@uform/antd/next): useFormEffect demo

- packages/react-schema-renderer/README.md
- packages/react-schema-renderer/README.zh-cn.md
[react-schema-renderer文档](https://github.com/alibaba/formily/blob/master/packages/react-schema-renderer/README.zh-cn.md#%E5%A6%82%E4%BD%95%E6%8E%A5%E5%85%A5-formformitem-%E7%BB%84%E4%BB%B6) 例子跑不起来，修改了下。
- CompatFormComponent函数多了个）结尾
- 单例注册方式那行少了个）结尾
> react-schema-renderer readme&readme.zh-cn Form/FormItem component demo bug fix

- packages/react-schema-editor/package.json
- packages/react-schema-editor/src/index.tsx
react-schema-editor使用中的问题
1. package依赖中没申明@ant-design/icons，导致直接启动报错。
2. 源码编辑的时候，编辑代码不符合json格式直接页面挂掉。
> React schema editor 优化

- packages/react-schema-renderer/src/__tests__/display.spec.tsx
- packages/react-schema-renderer/src/__tests__/validate.spec.tsx
- packages/react-schema-renderer/src/__tests__/value.spec.tsx
- packages/react-schema-renderer/src/__tests__/visible.spec.tsx
- packages/react-schema-renderer/src/components/SchemaField.tsx
- packages/react-schema-renderer/src/types.ts
schema模式的时候default、visible、display、required、rules增加表达式支持。
增加对应的单元测试。
ISchema  typescript类型修改，统一增加string类型。
复现地址 [https://codesandbox.io/s/upbeat-swanson-x9oqv](https://codesandbox.io/s/upbeat-swanson-x9oqv)
> 修复default、visible、display、required、rules不支持表达式

- packages/antd/src/adaptor/FormItem.tsx
- packages/next/src/adaptor/FormItem.tsx
mergedProps中包含了required字段，因此需要把实际的required赋值放到{...mergedProps}之后才行，否则会被覆盖
> fix: JSX Schema模块下FormItem在不可编辑时对label required处理问题修复

- packages/antd/src/types.ts
在 `antd` 中的 `FormItem` 中定义 `children` 为必传属性：
```tsx
// https://github.com/ant-design/ant-design/tree/master/components#L39
{
...
children: ChildrenType;
...
}
```
而在 `formily` 中应该是非必传的：
```tsx
<FormItem name="name" label="Name" component={Input} />
```
所以修改 `FormItem` 组件中 `children` 类型定义为可选属性。
> fix(antd): fix FormItem type definition

- packages/react-schema-editor/src/index.tsx
修改 `SchemaEditor` 组件属性 `showAntdComponents`， `showFusionComponents`，`customComponents` 的 TypeScript 类型定义为可选。
> fix(react-schema-editor): improve SchemaEditor types

- packages/antd-components/src/switch/index.tsx
修复 antd-components 的 `Switch` 组件缺少 default export
> fix(antd-components): Add default export for the antd

- packages/next-components/src/form-tab/index.tsx
1. 支持从外部传入defaultActiveKey
2. 当hiddenKeys长度变化时，重新计算activeKey
3. 解析defaultActiveKey的逻辑找到第一个非隐藏的tab
> fix parseDefaultActiveKey error

- docs/zh-cn/schema-develop/form-layout.md
- packages/antd-components/README.zh-cn.md
- packages/antd-components/src/form-tab/index.tsx
- packages/next-components/README.zh-cn.md
- packages/next-components/src/form-tab/index.tsx
1. 修复语法错误：两个逗号
2. 设置activeKey之前做检查，如果activeKey不存在则不设置
3. 解析默认activeKey时检查defaultActiveKey是否被隐藏，如果被隐藏则不设置
4. 同步antd-components中的FormTab 修改
> fix: FormTab components 

- packages/antd-components/README.zh-cn.md
- packages/antd/README.zh-cn.md
- 更新 `labelAlign` 类型，Ant Design Form 中 `labelAlign` 类型为  `left` | `right`
- 移除 Ant Design Form 中不支持的属性 `labelTextAlign`
> docs(antd/component): fix labelAlign type and remove labelTextAlign

- packages/antd/src/components/FormMegaLayout/ie.tsx
- packages/next/src/components/FormMegaLayout/ie.tsx
fix(antd): fix ie.tsx SSR bug
In ie.tsx, there is a line would break server side rendering, like below:
`const isIECompat = !('grid-column-gap' in document?.documentElement?.style)`
It will cause this error during SSR:
```
ReferenceError: document is not defined
at Object.<anonymous> (..../et_operation_platform/node_modules/@formily/antd-components/node_modules/@formily/antd/lib/components/FormMegaLayout/ie.js:4:48)
at Module._compile (internal/modules/cjs/loader.js:956:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
at Module.load (internal/modules/cjs/loader.js:812:32)
at Function.Module._load (internal/modules/cjs/loader.js:724:14)
at Module.require (internal/modules/cjs/loader.js:849:19)
at require (internal/modules/cjs/helpers.js:74:18)
at …
```
> fix(antd): fix ie.tsx ssr bug

- packages/core/src/externals.ts
原本`mutators.move`对数据的操作是“迁移”，将`fromIndex`移动到`toIndex`之后。但是之前一个版本变成了“交换”，将`fromIndex`与`toIndex`互换
回滚原先的`mutators.move`行为，并添加`mutators.swap`方法提供“交换”的能力
> fix: 回滚mutators.move行为

- packages/shared/package.json
更新依赖的`cool-path`到最新版本，以确保使用了`package-lock.json`锁定依赖版本的用户，在更新了最新的formily包后，能正常使用
> fix(shared): update cool-path version, ensure bug to be fixed

- packages/antd-components/src/array-table/index.tsx
修复使用 ArrayTable 且开启 draggable 时，报警告的问题 Each child in a list should have a unique "key" prop. in TableCell (created by TableRow)。
> fix(antd-components): missing 'key' prop warning when table draggable

- packages/react-shared-components/src/PreviewText.tsx
feat: preview-wrap
表单只读字段展示时，如果值是string且包含换行符\n, 则换行显示
> preview 文本如果包含换行符，换行展示

- packages/antd/README.zh-cn.md
- packages/antd/src/shared.ts
- packages/next/README.zh-cn.md
- packages/next/src/shared.ts
- packages/react-schema-renderer/src/shared/registry.ts
- packages/react-schema-renderer/src/types.ts
增加自定义 `PreviewText` 组件的注册能力，用于全局替换默认的 `PreviewText` 实现
> feat: add registerPreviewTextComponent

- packages/react-logic-diagram/docs/api.md
- packages/react-logic-diagram/docs/index.md
- packages/react-logic-diagram/package.json
- packages/react-logic-diagram/src/components/LogicDiagram.tsx
- packages/react-logic-diagram/src/types.ts
- yarn.lock
> refactor: 移除disabled, 调整属性命名, 调整 NodeTypes 枚举值

- packages/antd/README.zh-cn.md
- packages/next/README.zh-cn.md
修复 #1134 提到的问题。triggerDistance 不生效的实际原因是用途描述错误，根据代码，triggerDistance 应该表示按钮吸底距离。
> fix: 修改FormButtonGroup api描述(#1134)

- package.json
- packages/antd/copy.ts
- packages/antd/package.json
- packages/next/copy.ts
- packages/react/src/shared/render.ts
- yarn.lock
调整代码中直接使用 `require` 跟 ` antd/next` 的 `lib` 产物的处理，使 `formily` 可以适用于 `vite`、`snowpack`
> feat: applicable to vite

- packages/react-schema-renderer/src/shared/schema.ts
如题：schema.items 遗漏了 parent 的引用
> fix: schema.items 丢失 parent

- packages/vue/src/types/index.ts
> fix(vue): fix a type error in ISchemaMarkupFieldProps

- packages/core/src/__tests__/form.spec.ts
- packages/core/src/models/Field.ts
- packages/core/src/models/Form.ts
> feat(core): remove property of form values with undefined value

- packages/antd/docs/components/ArrayCollapse.md
- packages/antd/src/array-collapse/index.tsx
- 增加defaultOpenPanelCount配置
- 新增Panel默认展开
> feat(antd): add defaultOpenPanelCount

- packages/react/src/types.ts
---
让 `ReactComponentPropsByPathValue` 类型推导支持 `a.b` 格式。
> fix(react): fix ReactComponentPropsByPathValue type return error result

- packages/json-schema/src/types.ts
---
SchemaField 中的 component 跟 decorator 属性类型被 stringify 抹掉了。
> refactor(json-schema): refactor stringify type to fix literal type is erased

- packages/antd/src/array-collapse/index.tsx
> fix(antd): fix ArrayCollapse collapsed and expanded errors

- packages/next/docs/components/FormDialog.md
- packages/next/docs/components/FormDrawer.md
- packages/next/src/form-drawer/index.tsx
> feat(next): support form drawer get context from fusion

- packages/antd/package.json
- packages/next/package.json
- [x ] Make sure your code lints (`npm run lint`) - we've done our best to make sure these rules match our internal linting guidelines.
---
Add tree-shaking feature for ui framework.
> feat(antd/next): add tree-shaking support for antd/next

- packages/antd/src/submit/index.tsx
> feat(antd): improve Submit API

- packages/antd/src/reset/index.tsx
- packages/antd/src/submit/index.tsx
- packages/next/src/reset/index.tsx
- packages/next/src/submit/index.tsx
---
Fix typescript error when `onClick` is async function:
> fix(antd/next): fix event type incorrect of Submit

- packages/core/src/__tests__/field.spec.ts
- packages/core/src/models/Field.ts
- packages/core/src/models/VoidField.ts
- packages/core/src/shared/internals.ts
---
https://github.com/alibaba/formily/pull/1712 并没有根本上解决问题，如果是嵌套中的嵌套，还是会出问题
仔细想了一下，其实display应该是在父节点为visible状态的时候，selfDisplay优先级要高于父节点，如果父节点为hidden/none，那么子节点应该强制设置为其对应的值才行，这么看来显隐模型真的是表单模型中的重要概念了
> chore(core): improve display model

- packages/react/src/components/RecursionField.tsx
> fix(react): fix x-content is not work with array type

- scripts/build-global.ts
---
在 `node v16.0.0 ` 上执行 `yarn build` 发生错误:
```node
@formily/reactive@2.0.0-beta.76 build:global
> ts-node ../../scripts/build-global
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run build stderr:
src/index.ts → dist/formily.reactive.umd.development.js...
(node:10388) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at C:\Users\liuwei\Desktop\github\formily\node_modules\rollup-plugin-typescript2\node_modules\tslib\package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where …
```
> build: fix build global may be failed

- packages/antd/docs/components/FormLayout.md
- packages/antd/src/form-item/style.less
- packages/next/docs/components/FormLayout.md
- packages/next/src/form-item/main.scss
> fix(antd/next): fix tooltip  style incorrect of formitem

- packages/antd/src/form-grid/index.tsx
- packages/next/src/form-grid/index.tsx
---
in antd and next package, make form-grid and layout props optional with default value
> fix(antd/next): form-grid and layout props optional with default value

- designable/antd/src/locales/en-US.ts
- designable/antd/src/locales/zh-CN.ts
- designable/antd/src/schemas/Upload.ts
---
expose upload component's textContent property in setting form
> refactor(designable-antd): expose upload component's textContent property in setting form

- designable/antd/src/locales/zh-CN.ts
- designable/antd/src/schemas/Upload.ts
- designable/setters/src/components/ReactionsSetter/declarations.ts
- designable/setters/src/components/ReactionsSetter/helpers.ts
- designable/setters/src/components/ReactionsSetter/index.tsx
- designable/setters/src/components/ReactionsSetter/styles.less
- docs/guide/advanced/linkages.md
- docs/guide/advanced/linkages.zh-CN.md
- packages/json-schema/src/transformer.ts
- packages/reactive/docs/api/autorun.md
- packages/reactive/src/__tests__/array.spec.ts
- packages/reactive/src/__tests__/autorun.spec.ts
- packages/reactive/src/array.ts
- packages/reactive/src/autorun.ts
- packages/reactive/src/datatree.ts
- packages/reactive/src/reaction.ts
- packages/reactive/src/types.ts
> feat(reactive): support autorun.memo/autorun.effect

- packages/path/src/__tests__/match.spec.ts
- packages/path/src/matcher.ts
- packages/path/src/shared.ts
---
I remembered why I used `[...field.path.toArr(), name]` instead of `` `${field.path}.${name}` `` while writing this document, https://github.com/alibaba/formily/pull/1727#issuecomment-875318609
It was because events listening to pattern `${field.path}.${name}` will fail to dispatch if the component is used as an item of an array field, so I usually avoid writing in this "recommended way". Here is a reproduce, https://codesandbox.io/s/objective-wilbur-n2fqe
> fix(path): fix segments match

- package.json
- packages/antd/__tests__/sideEffects.spec.ts
- packages/antd/package.json
- packages/next/__tests__/sideEffects.spec.ts
- packages/next/package.json
> fix(antd): fix sideEffects mismatch when use babel-plugin-import (#1842)

- packages/element/src/__builtins__/shared/portal.ts
> fix(element): fix portal destroy

- designable/antd/playground/widgets/ActionsWidget.tsx
- packages/next/src/select/index.tsx
---
- formily/next: Fix that `Select` can't be selected when the children of dataSource is an empty array.
- designable/antd: Fix the spelling error of the word `English`.
> fix(next/designable-antd): fix Select bug && designable-antd spelling error

- packages/next/src/form/index.tsx
---
Form: If the language of the context is undefined, use `zh-CN` as the default language.
> fix(next): add the default language when the language is undefined

- packages/next/src/form-tab/index.tsx
---
Fix that when `activeKey` is undefined, `FormTab` is regarded as a controlled component.
> fix(next): fix FormTab activeKey bug

- packages/core/src/__tests__/form.spec.ts
- packages/core/src/models/Field.ts
- packages/core/src/shared/internals.ts
> test(core): add designable tests

- packages/vue/src/__tests__/schema.json.spec.ts
- packages/vue/src/components/RecursionField.ts
---
fix: prop "scope" of SchemaField not work with reactions
> fix(vue): prop "scope" of SchemaField not work with x-reactions

- packages/reactive/src/__tests__/autorun.spec.ts
- packages/reactive/src/autorun.ts
- packages/reactive/src/reaction.ts
> fix(reactive): fix dispose omission clean pendding reactions

- packages/reactive-react/src/observer.ts
---
The 2nd generic param of `observer` should be optional.
```diff
- const Comp = observer<Props, {}>(props => null);
+ const Comp = observer<Props>(props => null);
```
> fix(reactive-react): fix observer 2nd generic type

- packages/vue/docs/demos/questions/scoped-slot.vue
- packages/vue/src/__tests__/schema.json.spec.ts
- packages/vue/src/components/ReactiveField.ts
using Vue 2 `render(h, {props})` to pass the scoped props.
---
增加 Vue 版本的作用域插槽（基于 x-content 属性）支持
> feat(vue): support scoped slot

- packages/core/docs/api/entry/FormEffectHooks.md
- packages/core/docs/api/entry/FormEffectHooks.zh-CN.md
> docs: add notice for onFormValuesChange

- packages/path/src/__tests__/match.spec.ts
- packages/path/src/__tests__/parser.spec.ts
- packages/path/src/parser.ts
- packages/path/src/tokens.ts
> fix(path): fix path match destructor

- packages/antd/src/array-table/index.tsx
- packages/core/src/__tests__/array.spec.ts
- packages/core/src/shared/constants.ts
- packages/core/src/shared/internals.ts
- packages/core/src/types.ts
- packages/react/src/components/ObjectField.tsx
> fix(core): fix array unshift with incomplete elements

- packages/antd/src/form-grid/index.tsx
- packages/antd/src/form-layout/index.tsx
- packages/next/src/form-grid/index.tsx
- packages/next/src/form-layout/index.tsx
> fix(antd/next): fix props.prefix is not work for FormGrid/FormLayout

- packages/element/docs/demos/guide/select/template-async.vue
- packages/element/src/form-layout/style.scss
- packages/element/src/select/index.ts
---
fix(element): fix select label error
feat(element): add form layout inline support
> fix(element): fix select label error

- packages/vue/src/__tests__/field.spec.ts
- packages/vue/src/components/ReactiveField.ts
…ritten rather than merged
---
fix the problem that the component class name will be overwritten rather than merged
> fix(vue): fix the problem that the component class name will be overwritten rather than merged

- packages/core/src/models/Field.ts
- packages/reactive/src/__tests__/autorun.spec.ts
- packages/reactive/src/handlers.ts
---
Fixed #2344 
这个问题是因为如果一次原子型set操作没有在batch模式下执行的话，如果有多个computed值依赖操作对象的不同属性，同时在autorun中又依赖了这些computed值，就会导致用户认为是一次原子操作，但是autorun执行却执行了多次，而且还会导致执行的时候，computed的值，是按顺序一个个透出的，其实应该是一次性透出，同时该问题是之前一直存在的问题，只是因为rc14版本的优化，该问题就很轻易的暴露出来了
> fix(reactive): fix computed value can not get real value

- tsconfig.json
---
Set the `inlineSources` option to `true` in `tsconfig.json`.
This is because in the current source map file, I found the sources field that is pointing to the source location (such as `"sources":["../src/index.ts"]` in https://cdn.jsdelivr.net/npm/@formily/react@2.0.0-rc.18/esm/index.js.map). But the `src` folder is not inclued in the published package.
When using some esm bundlers such as `Vite`, the dev server could not find the source file and finally response error with code 404, which means that I can not debug the formily source in browser with source map enabled when using Vite.
> build(sourcemap): add "sourcesContent" to the output source map

- packages/vue/src/__tests__/form.spec.ts
- packages/vue/src/components/FormProvider.ts
- packages/vue/src/hooks/useInjectionCleaner.ts
---
Clear injections out of FormProvider.
> feat(vue): add injectionCleaner to FormProvider

- packages/core/src/__tests__/field.spec.ts
- packages/core/src/shared/internals.ts
> fix(core): validator repeat call

- packages/antd/tsconfig.json
- packages/benchmark/tsconfig.json
- packages/core/tsconfig.json
- packages/element/tsconfig.json
- packages/grid/tsconfig.json
- packages/next/tsconfig.json
- packages/react/tsconfig.json
- packages/reactive-react/src/shared/gc.ts
- packages/reactive-react/src/shared/global.ts
- packages/reactive-react/tsconfig.json
- packages/shared/tsconfig.json
---
Add `ESNext` and `DOM` lib to TS compiler options to avoid TS compilants about unknown "WeakMap", “symbol”, "window"，etc.
`ESNext` lib is added to all the packages, while the `DOM` lib is added only to the packages using DOM APIs.
So we can remvoe types  patch for `FinalizationRegistry`
> chore: add ESNext and DOM lib to TS compiler options

- packages/reactive/src/annotations/computed.ts
- packages/reactive/src/checkers.ts
- packages/shared/src/checkers.ts
> chore: improve code style

- packages/core/src/models/Field.ts
- packages/core/src/shared/internals.ts
- packages/reactive/src/__tests__/batch.spec.ts
- packages/reactive/src/autorun.ts
---
之前给reaction scheduler加了untrack，但是如果在scheduler里调用setState，会影响数据收集，还是需要回退回去，不过之前加untrack是为了解决 https://github.com/alibaba/formily/pull/2563 这个问题，所以针对该问题单独做untrack即可
> fix(reactive): fix reaction scheduler prevent setState rerender

- packages/antd/docs/components/FormItem.md
- packages/antd/docs/components/FormItem.zh-CN.md
- packages/antd/src/form-item/index.tsx
---
针对这种排版的错乱，需要Popover组件的getPopupContainer来指定外部容器
因此我给@formily/antd-component的FormItem组件新增了getPopupContainer，用来解决上面的问题
> feat(antd-component): provide `getPopupContainer` prop for `FormItem` when use popover feedback

- packages/antd/package.json
- packages/grid/package.json
- packages/grid/src/index.ts
- packages/next/package.json
> fix(grid): add resize-observer-polyfill

- packages/core/src/__tests__/array.spec.ts
- packages/core/src/models/BaseField.ts
- packages/core/src/shared/internals.ts
> fix(core): fix array remove can not auto clean initialValue

- .gitignore
- packages/vue/bin/formily-vue-fix.js
- packages/vue/bin/formily-vue-switch.js
- packages/vue/package.json
- packages/vue/scripts/postinstall.js
- packages/vue/scripts/switch-cli.js
- packages/vue/scripts/utils.js
- packages/vue/src/components/ArrayField.ts
- packages/vue/src/components/Field.ts
- packages/vue/src/components/FormConsumer.ts
- packages/vue/src/components/FormProvider.ts
- packages/vue/src/components/ObjectField.ts
- packages/vue/src/components/ReactiveField.ts
- packages/vue/src/components/RecursionField.ts
- packages/vue/src/components/SchemaField.ts
- packages/vue/src/components/VoidField.ts
- packages/vue/src/shared/connect.ts
- packages/vue/src/shared/fragment.ts
- packages/vue/src/types/index.ts
- packages/vue/src/types/vue2.ts
- packages/vue/src/types/vue3.ts
- packages/vue/tsconfig.types.json
- yarn.lock
---
- Add auto switching for types of @formily/vue in postinstall hook.
- Add `formily-vue-fix` & `formily-vue-switch` command. (Just like [vue-demi](https://github.com/vueuse/vue-demi) does)
- Removed dependencies of `@type-helper/vue2` & `@type-helper/vue3` which may cause type confusion.
- Exports of `Vue2Components` may be deprecated.
> refactor(vue): switch type files for vue2/vue3 in postinstall

- packages/antd/__tests__/moment.spec.ts
- packages/antd/src/__builtins__/moment.ts
- packages/next/__tests__/moment.spec.ts
- packages/next/src/__builtins__/moment.ts
> fix(antd-component): fix tool methods and provide simple unit tests

- packages/antd/src/form-item/index.tsx
- packages/antd/src/form-layout/useResponsiveFormLayout.ts
- packages/element/src/form-layout/useResponsiveFormLayout.ts
- packages/next/src/form-item/index.tsx
- packages/next/src/form-layout/useResponsiveFormLayout.ts
…FormItem useOverflow update
---
> feat(next/antd/vue): add useResponsiveFormLayout fault tolerance and FormItem useOverflow update

- packages/antd/src/select/index.tsx
---
在 @typescript-eslint/eslint-plugin 1.*的版本会报错
Type '{ name: string; title: string; required: true; "x-decorator": string; "x-component": string; "x-component-props": { placeholder: string; }; }' is not assignable to type 'ISchemaTypeFieldProps<{ Input: ComposedInput; Select: ForwardRefExoticComponent<Pick<Partial<SelectProps<SelectValue> & { ref?: Ref<RefSelectProps>; }>, "style" | ... 120 more ... | "internalProps"> & RefAttributes<...>>; ... 4 more ...; Loader: any; }, "FormItem", "Select">'.
对Select组件增加ts
> feat(antd): add ts

- packages/core/src/__tests__/field.spec.ts
- packages/core/src/models/Query.ts
- packages/element/src/checkbox/index.ts
> fix(core): fix query sibling value is not work

- packages/vue/src/shared/connect.ts
---
fix https://github.com/alibaba/formily/discussions/2807
add component name in connect API
> fix(vue): add component name in connect

- packages/antd/docs/components/PreviewText.md
- packages/antd/docs/components/PreviewText.zh-CN.md
- packages/antd/src/preview-text/index.tsx
> fix(antd): fix use treeData props for PreviewText.TreeSelect

- packages/vue/src/__tests__/schema.json.spec.ts
- packages/vue/src/__tests__/schema.markup.spec.ts
- packages/vue/src/components/ArrayField.ts
- packages/vue/src/components/Field.ts
- packages/vue/src/components/ObjectField.ts
- packages/vue/src/components/ReactiveField.ts
- packages/vue/src/components/RecursionField.ts
- packages/vue/src/components/VoidField.ts
---
Support 'x-slot' in RecursionField. This feature provides [Slots](https://v2.vuejs.org/v2/guide/components-slots.html) for object/void type field's component.
> feat(vue): support x-slot

- packages/element/src/form-item/index.ts
---
Remove Element FormItem feedback function `split` for `selfErrors`, `selfWarnings`, `selfSuccesses`。
移除 Elemnt FormItem 组件对于错误、提醒以及成功消息的 split 方法处理，因为在后面已经进行了处理
https://github.com/alibaba/formily/blob/1ef47b0a0c3359f94449d53850354f0b2a9d8971/packages/element/src/form-item/index.ts#L523 
见示例：
https://codesandbox.io/s/strange-edison-s48o0y?file=/src/App.vue
> fix(element-components): fix formitem feedback msg

- packages/reactive-vue/src/hooks/useObserver.ts
> fix(reactive-vue): fix vue3 render dependency collection broken

- packages/antd/docs/components/PreviewText.md
- packages/antd/docs/components/PreviewText.zh-CN.md
- packages/antd/src/preview-text/index.tsx
- packages/next/docs/components/PreviewText.md
- packages/next/docs/components/PreviewText.zh-CN.md
- packages/next/src/preview-text/index.tsx
> fix(next/antd): fix single value invalid in PreviewText.Cascader

- packages/core/src/__tests__/array.spec.ts
- packages/core/src/shared/internals.ts
> fix(core): fix array field remove with memory leak

- packages/antd/src/array-base/index.tsx
- packages/next/src/array-base/index.tsx
> fix(antd/next): fix array string field addition logic

- packages/antd/package.json
- packages/next/package.json
- packages/react/package.json
- packages/reactive-react/package.json
- yarn.lock
---
- Add peerDependenciesMeta
- upgrade react-sticky-box to 1.0.2
> build: add peerDependenciesMeta and upgrade react-sticky-box to 1.0.2

- packages/antd/src/form-step/index.tsx
- packages/next/src/form-step/index.tsx
---
当前调用`formStep.setCurrent(1)` 时，因为没有调`setDisplay`, 导致跳到那一步了，但是域都没显示出来，依然是hidden状态
> fix(antd/next): form step setcurrent bug

- packages/reactive/src/tracker.ts
---
考虑到Tracker的定位，其实就应该只是依赖追踪，唯一推荐响应过程中并操作数据的，只有autorun，虽然Tracker中也支持，但没必要使用batch，因为React的setState执行会同步触发render函数执行，这样相当于每次数据响应都是得在渲染函数执行完才响应，其实也不合理
> feat(reactive): remove reactive tracker default batch

- packages/path/src/__tests__/match.spec.ts
- packages/path/src/matcher.ts
> fix(path): fix range all match is not expect
